### ISSUE TITLE
Not triggering on commits

### ISSUE THREAD

**Issue by wabberz** [Commit451/skyhook#10]
I set your script up on my server to relay GitLab commit messages to Discord, and clicking the Test button triggers it, and so does editing wiki pages (though they aren't formatted as nicely) - but nothing happens on commits.

I'm using GitLab 9.0.5 by the way.

(oh, and Discord gives me https://canary.discordapp.com/api/webhooks/ urls - but just removing the canary part makes them work with your script, so it's not really an issue)

**Comment by Jawnnypoo** [comment]
Strange... does it work for when issues are opened and other events like that?

**Comment by wabberz** [comment]
Hm, I put used a testscript to see what happens and it turns out GitLab doesn't even trigger it for some reason, so the problem is not with your script. Sorry for your trouble!

**Comment by Jawnnypoo** [comment]
No worries!
