### ISSUE TITLE
Allow domain name configuration

### ISSUE THREAD

**Issue by lutangar** [Commit451/skyhook#100]
When skyhook is self-hosted, we should be able to change the domain name.

At the moment **skyhook.glitch.me** is hardcoded in `skyhook/public/client.js`:
```
discordHookUrl = discordHookUrl.replace("discordapp.com", "skyhook.glitch.me");
```

One possible solution could used ENV variables via https://github.com/motdotla/dotenv for example.
It would also allow environment variables replacement when running a docker container.

**Comment by Jawnnypoo** [comment]
Good point! This would be a good addition.

**Comment by dscalzi** [comment]
The url is now determined by the window's origin.

```javascript
discordHookUrl = discordHookUrl.replace('https://discordapp.com', window.location.origin);
```
