### ISSUE TITLE
[Gitlab] Merge Request event

### ISSUE THREAD

**Issue by lutangar** [Commit451/skyhook#101]
When testing a **Merge request event** on a hook, **Gitlab** shows the following error:
```
Hook executed successfully but returned HTTP 400 Bad Request
```
> For the record every other test events went smoothly.

Furthermore, the test event doesn't reach **discord**.

* GitLab Community Edition 11.1.1 94b9323

**Comment by dscalzi** [comment]
The only time skyhook returns 400 is when the url is malformed (which I'm assuming it isn't) or when we get an error while sending the embed to discord. The latter is not really an appropriate event to return 400. It is more indicative of a 502 Bad Gateway.


> A 502 Bad Gateway indicates that the edge server (server acting as a proxy) was not able to get a valid or any response from the origin server (also called upstream server)


I pushed a commit to clear this up. https://github.com/Commit451/skyhook/blob/master/src/index.ts#L148

Please try the test again. If you still get 400, ensure your url is not malformed. If it changes to 502, send me some additional information (full error log, if present).

**Comment by dscalzi** [comment]
Closing due to lack of followup.
