### ISSUE TITLE
Error parsing Heroku

### ISSUE THREAD

**Issue by AladMocu** [Commit451/skyhook#106]
I got:
 ![captura](https://user-images.githubusercontent.com/25905130/45499070-32edc280-b741-11e8-8c9c-a9e85c55361a.PNG)

and the heroku webhook post was:
`... "app":{"id":"afedae50-e9a8-4bc1-abc6-6a63caf8bef4","name":"paypal-discord-bot"} ...`

**Comment by dscalzi** [comment]
Will be fixed next time @Jawnnypoo syncs the site.

**Comment by Jawnnypoo** [comment]
Done!

**Comment by dscalzi** [comment]
Send the full payload please.

**Comment by AladMocu** [comment]
```js
{"id":"69ba4e4d-79f8-4bd1-b57c-4ab8d9a72967","created_at":"2018-09-16T14:42:05Z","data":{"id":"3650ba4e-9e7e-4927-a391-b01156c53742","app":{"id":"afedae50-e9a8-4bc1-abc6-6a63caf8bef4","name":"paypal-discord-bot"},"release":{"id":"4fbd32c4-e9e5-4409-8779-5c702b4f4bc9","version":8},"command":"npm start","size":"Free","exit_status":null,"management":"formation","state":"down","type":"web","name":"web.1"},"actor":{"id":"1030c06a-bcbe-4738-9134-89af5c717fb1","email":"noreply+webhooks@heroku.com"},"previous_data":{},"published_at":null,"resource":"dyno","action":"destroy","version":"application/vnd.heroku+json; version=3","webhook_metadata":{"attempt":{"id":"d71e5db0-9111-406e-8037-5c6ab1ca2e1c"},"delivery":{"id":"3726e949-5699-477e-b029-773f6ecace6b"},"event":{"id":"69ba4e4d-79f8-4bd1-b57c-4ab8d9a72967","include":"dyno"},"webhook":{"id":"961e2109-6f32-4c91-9a3f-1fcd9f1240ec"}}}```

**Comment by dscalzi** [comment]
Are you sure you've setup your webhook with heroku? This is completely different from their documentation.

**Comment by AladMocu** [comment]
yes, Im sure: 
![webhooks](https://user-images.githubusercontent.com/25905130/45684774-fccb8c80-bb0c-11e8-92b4-01f8884cd9de.JPG)

**Comment by Jawnnypoo** [comment]
I think maybe stuff like `data` is custom to the project:
https://devcenter.heroku.com/articles/app-webhooks-schema

It seems like `app` should be a top level payload thing, but it looks like it is contained within `data` here. Maybe we can just check both places and see if one of them resolves?

I went ahead and deleted your image above, since it contained the parts of your webhook that people could use to spam the hook. Try to keep them secret!

**Comment by dscalzi** [comment]
I think heroku added a new webhook type and is phasing out the old one. 
See: https://blog.heroku.com/heroku-webhooks

It looks like the app webhook format covers what the deploy webhook does and then some. Perhaps we should drop support for the deploy format and just support this new one? The new format can be found here https://devcenter.heroku.com/articles/app-webhooks#receiving-webhooks. Oddly, it's not the same as what @AladMocu posted. Perhaps users are required to resetup their webhooks using their new endpoint.

Alternatively we can include some checks to accomidate each of these formats.

Let me know your thoughts @Jawnnypoo, I'll be free to implement whatever we settle on.

**Comment by Jawnnypoo** [comment]
Yep, clean break to the new format is the best way to go in my opinion. Thanks for looking into this!

**Comment by Jawnnypoo** [comment]
Oops, didn't mean to close :P

**Comment by kot83** [comment]
Do we have an ETA on this? By the way, personally I think that having skyhook send an error message is better than 'undefined'.

**Comment by Jawnnypoo** [comment]
This should be good now. Tell me what you guys think. I am not sure if this will work in practice, but I think it will.
