### ISSUE TITLE
Gitlab Error

### ISSUE THREAD

**Issue by ezzzly** [Commit451/skyhook#107]
An error has occured on skyhook for your webhook with provider gitlab. Maybe you can copy/paste or screenshot this error if there is no sensitive information and open an issue on the skyhook GitHub.

Error: "TypeError: Cannot read property 'name' of undefined\n at GitLab.projectFromBody (/app/dist/provider/GitLab.js:193:46)\n at GitLab.<anonymous> (/app/dist/provider/GitLab.js:42:34)\n at Generator.next (<anonymous>)\n at /app/dist/provider/GitLab.js:6:71\n at new Promise (<anonymous>)\n at __awaiter (/app/dist/provider/GitLab.js:2:12)\n at GitLab.push (/app/dist/provider/GitLab.js:38:16)\n at GitLab.<anonymous> (/app/dist/provider/BaseProvider.js:57:33)\n at Generator.next (<anonymous>)\n at fulfilled (/app/dist/provider/BaseProvider.js:3:58)"

**Comment by dscalzi** [comment]
Will be fixed next time @Jawnnypoo syncs the site.

**Comment by Jawnnypoo** [comment]
Done!
