### ISSUE TITLE
Issue with Jira

### ISSUE THREAD

**Issue by Jawnnypoo** [Commit451/skyhook#110]
From Twitter: 

![dqscs_nxcaetpq9](https://user-images.githubusercontent.com/1459320/47445018-77776f80-d77d-11e8-9d5c-18e923768a19.jpg)

@dscalzi Would you like to look into this one?

**Comment by dscalzi** [comment]
What is the jira webhook triggered for? This is not possible if it's configured for issue related webhooks.

**Comment by Wild1145** [comment]
I've been having the same issue but assumed I'd screwed something up with setting up the JIRA Server Webhook...

**Comment by antondemanoff** [comment]
Get the same errors too. Looks like current realization doesn't work with self hosted Jira, only with cloud.

**Comment by justinas-kazanavicius** [comment]
I am also getting the same on self hosted

**Comment by justinas-kazanavicius** [comment]
I am also getting the same errors on a self hosted server

**Comment by stanleyyork11** [comment]
![image](https://user-images.githubusercontent.com/3420196/49087191-3f68be00-f24e-11e8-95ee-06828b132a33.png)
This was triggered during a comment addition on an issue in Jira Software Cloud.

**Comment by stanleyyork11** [comment]
![img_1075](https://user-images.githubusercontent.com/3420196/49238434-51866000-f3f8-11e8-9eaf-4d43c6b0a772.jpeg)
This error now seems to be triggering randomly regardless of what I am updating on Jira.

**Comment by dscalzi** [comment]
Some of those issues are likely related to non-issue related actions being performed on Jira. At this time, we are only supporting issue related events. If you would like to expand the coverage of the Jira provider, feel free to submit a PR.
