### ISSUE TITLE
Issue with Trello

### ISSUE THREAD

**Issue by Bioblaze** [Commit451/skyhook#111]
An error has occured on skyhook for your webhook with provider trello. Maybe you can copy/paste or screenshot this error if there is no sensitive information and open an issue on the skyhook GitHub.

Error: "TypeError: Cannot read property 'name' of undefined\n at Trello.<anonymous> (/app/dist/provider/Trello.js:813:115)\n at Generator.next (<anonymous>)\n at /app/dist/provider/Trello.js:6:71\n at new Promise (<anonymous>)\n at __awaiter (/app/dist/provider/Trello.js:2:12)\n at Trello.updateList (/app/dist/provider/Trello.js:809:16)\n at Trello.<anonymous> (/app/dist/provider/BaseProvider.js:57:33)\n at Generator.next (<anonymous>)\n at fulfilled (/app/dist/provider/BaseProvider.js:3:58)\n at process._tickCallback (internal/process/next_tick.js:68:7)"

**Comment by KJP12** [comment]
Yes; I just got 4 come through myself. The error:
```js
Error: "TypeError: Cannot read property 'name' of undefined\n at Trello.<anonymous> (/app/dist/provider/Trello.js:813:115)\n at Generator.next (<anonymous>)\n at /app/dist/provider/Trello.js:6:71\n at new Promise (<anonymous>)\n at __awaiter (/app/dist/provider/Trello.js:2:12)\n at Trello.updateList (/app/dist/provider/Trello.js:809:16)\n at Trello.<anonymous> (/app/dist/provider/BaseProvider.js:57:33)\n at Generator.next (<anonymous>)\n at fulfilled (/app/dist/provider/BaseProvider.js:3:58)\n at process._tickCallback (internal/process/next_tick.js:68:7)"```

Attempted to manually cleaned the stack:
```js
Error: "TypeError: Cannot read property 'name' of undefined
at Trello.<anonymous> (/app/dist/provider/Trello.js:813:115)
at Generator.next (<anonymous>)
at /app/dist/provider/Trello.js:6:71
at new Promise (<anonymous>)
at __awaiter (/app/dist/provider/Trello.js:2:12)
at Trello.updateList (/app/dist/provider/Trello.js:809:16)
at Trello.<anonymous> (/app/dist/provider/BaseProvider.js:57:33)
at Generator.next (<anonymous>)
at fulfilled (/app/dist/provider/BaseProvider.js:3:58)
at process._tickCallback (internal/process/next_tick.js:68:7)"```

If you're curious as to which board I got this in, it would be board https://trello.com/b/prGpkOsu, piping to Discord webhook `422290386225070090` and Trello Webhook `5aa4e6aec7b0d738c9df9937`. Last few actions at the time of receiving the error & time of writing.

![image](https://user-images.githubusercontent.com/8528256/49706481-fd8b3080-fbda-11e8-8fa7-4db1f8d59813.png)

**Comment by ChineseMarc** [comment]
I will try to fix this issue and i will make pull request if i fix it

**Comment by KJP12** [comment]
I think I narrowed it down to when you archive something on Trello. I got that error go through when I archived a list.

**Comment by dscalzi** [comment]
Will be fixed next time @Jawnnypoo syncs the site.

**Comment by Jawnnypoo** [comment]
Synced now
