### ISSUE TITLE
Improve the AppVeyor responses.

### ISSUE THREAD

**Issue by justalemon** [Commit451/skyhook#117]
Currently, the embed shown by SkyHook with AppVeyor as the origin shows little to no important information:
![image](https://user-images.githubusercontent.com/11861253/51451594-d153eb00-1d14-11e9-9f89-ee64ca1dfa5f.png)
Adding the following is going to really improve things up:
* Build version (`buildVersion`)
* Repository system (`repositoryProvider`)
* Hash of the commit being built (`commitId`)
* Author of the commit being built (`commitAuthor`)
* Compilation messages (`compilationMessages`)
* If there is only one job and one artifact, the permalink to it (`jobs[0]`/`artifacts[0]`/`permalink`)

**Comment by dscalzi** [comment]
Feel free to submit a PR

**Comment by justalemon** [comment]
JS/TS is not my forte, but I might try.

**Comment by dscalzi** [comment]
Basically just pull, run `npm install`, go to AppVeyor.ts and make the desired changes. All webhook attributes are available under `this.body`.
