### ISSUE TITLE
Error with Large Push of Files.

### ISSUE THREAD

**Issue by Bioblaze** [Commit451/skyhook#121]
When too many files are included in the Push, this happens.

`Hook executed successfully but returned HTTP 413 <!DOCTYPE html> <html lang="en"> <head> <meta charset="utf-8"> <title>Error</title> </head> <body> <pre>PayloadTooLargeError: request entity too large<br> &nbsp; &nbsp;at readStream (/app/node_modules/raw-body/index.js:155:17)<br> &nbsp; &nbsp;at getRawBody (/app/node_modules/raw-body/index.js:108:12)<br> &nbsp; &nbsp;at read (/app/node_modules/body-parser/lib/read.js:77:3)<br> &nbsp; &nbsp;at jsonParser (/app/node_modules/body-parser/lib/types/json.js:135:5)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at trim_prefix (/app/node_modules/express/lib/router/index.js:317:13)<br> &nbsp; &nbsp;at /app/node_modules/express/lib/router/index.js:284:7<br> &nbsp; &nbsp;at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)<br> &nbsp; &nbsp;at next (/app/node_modules/express/lib/router/index.js:275:10)<br> &nbsp; &nbsp;at expressInit (/app/node_modules/express/lib/middleware/init.js:40:5)</pre> </body> </html>`

**Comment by dscalzi** [comment]
For which type of webhook?

**Comment by Bioblaze** [comment]
Github

**Comment by dscalzi** [comment]
Is this a frequent issue? I believe we can bump the payload length limit but it might be better to keep it as is to prevent overwhelming the application.
