### ISSUE TITLE
Error when sending webhook from Jira workflow transition

### ISSUE THREAD

**Issue by taradinoc** [Commit451/skyhook#128]
I'm using Jira Cloud, and this happened when I resolved an issue using a workflow transition:

> Skyhook Error
> An error has occured on skyhook for your webhook with provider jira. Maybe you can copy/paste or screenshot this error if there is no sensitive information and open an issue on the skyhook GitHub.
> 
> Error: "TypeError: Cannot read property 'startsWith' of undefined\n at Jira.<anonymous> (/app/dist/provider/Jira.js:29:40)\n at Generator.next (<anonymous>)\n at /app/dist/provider/Jira.js:6:71\n at new Promise (<anonymous>)\n at __awaiter (/app/dist/provider/Jira.js:2:12)\n at Jira.parseData (/app/dist/provider/Jira.js:27:16)\n at Jira.<anonymous> (/app/dist/provider/BaseProvider.js:57:33)\n at Generator.next (<anonymous>)\n at /app/dist/provider/BaseProvider.js:6:71\n at new Promise (<anonymous>)"

**Comment by taradinoc** [comment]
Here's the (anonymized) JSON content Jira is sending:

https://gist.github.com/taradinoc/f468d89d0bb14a01a4a7c011e4122600

**Comment by dscalzi** [comment]
What kind of transition is this? The body does not contain `webhookEvent` so I'm not sure how we're supposed to be able to process it.

I'm going to fix this by returning nothing if we don't get an event.
