### ISSUE TITLE
https://skyhook.glitch.me is down

### ISSUE THREAD

**Issue by relanuza** [Commit451/skyhook#133]
I can't access the site. Is this permanently or just a hiccup?

**Comment by Jawnnypoo** [comment]
Glitch.me is down right now

**Comment by Jawnnypoo** [comment]
https://twitter.com/glitch/status/1191412617551777793

**Comment by zencodedevs** [comment]
it is down again 👎

**Comment by Jawnnypoo** [comment]
Its down for good, I took it offline. Please update to skyhookapi.com
