### ISSUE TITLE
GitLab merge request hook event throws an error.

### ISSUE THREAD

**Issue by HeyBanditoz** [Commit451/skyhook#135]
Says `Net::ReadTimeout` and Internal Erorr on the status.

**Comment by szczepix** [comment]
I have a same error:
![image](https://user-images.githubusercontent.com/1363477/69494877-fbd87c80-0ec0-11ea-9bf6-f50681babd26.png)

**Comment by Kyusetzu** [comment]
Same problem here.
It appears that any connect (regardless of push, merge, issue or comment, etc)

GitLab always prints out that error.

**Comment by HeyBanditoz** [comment]
Seems to be an uptime issue with this service specifically

**Comment by Rainnerz** [comment]
I also get this error. Downtime maybe?

**Comment by Repooc** [comment]
I been running this on my own server with similar issues.  We use it to post information from gitlab to our discord and been having the issues as well.  So I don't think it's isolated to just skyhook.glitch.me

**Comment by n0minal** [comment]
Seems like skyhook is broken for gitlab, I'm also having this issue.

**Comment by HeyBanditoz** [comment]
[Here's](https://dickswordapp.com/) an alternative I found.

**Comment by TehnoMag** [comment]
Seems something change in the embeded payload. I tryed to reproduce functionality via simple POST requests to the discord server and i get this issue to. Only with discord.py it worked.

**Comment by dscalzi** [comment]
Feel free to submit a PR
