### ISSUE TITLE
Rollbar Support

### ISSUE THREAD

**Issue by AbdelrahmanMohamedDesoky** [Commit451/skyhook#139]
Hello, 

I'd like to request rollbar support with skyhook glitch if possible.

API Reference: https://docs.rollbar.com/docs/webhooks

This sure would be much appreciated! as a lot of people depend on Rollbar for their whole Integrations.

**Comment by dscalzi** [comment]
Feel free to submit a PR as well

**Comment by Jawnnypoo** [comment]
Added, but I don't use Rollbar, so can you give some feedback on the integration? Thanks!
