### ISSUE TITLE
HTTP 500 Error received from Skyhook when using /bitbucket

### ISSUE THREAD

**Issue by ddouglas493** [Commit451/skyhook#14]
Hello,

I am attempting to use your service as a proxy between Discord and Bitbucket. I enter my generated webhook from Bitbucket into your website and then took the generated skyhook webhook and plugged it into Bitbucket. This is the url:

> https://skyhook.glitch.me/api/webhooks/310283783116947459/HEY8xkoYCZEEn1iXRvsW2-OHQkcAU5M9PJPd-_G3VtxE--2EqqtVnjtU2amrHtKPQaKm/bitbucket

This is the response that Bitbucket got back. 

```

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>TypeError: Cannot read property &#39;display_name&#39; of undefined<br> &nbsp; &nbsp;at Object.parse (/app/providers/bitbucket.js:34:158)<br> &nbsp; &nbsp;at /app/server.js:46:23<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at next (/app/node_modules/express/lib/router/route.js:137:13)<br> &nbsp; &nbsp;at Route.dispatch (/app/node_modules/express/lib/router/route.js:112:3)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at /app/node_modules/express/lib/router/index.js:281:22<br> &nbsp; &nbsp;at param (/app/node_modules/express/lib/router/index.js:354:14)<br> &nbsp; &nbsp;at param (/app/node_modules/express/lib/router/index.js:365:14)<br> &nbsp; &nbsp;at param (/app/node_modules/express/lib/router/index.js:365:14)</pre>
</body>
</html>
```

The request: https://pastebin.com/qdZe7968

**Comment by Mythen96** [comment]
I will have a look on it later this day.

**Comment by Mythen96** [comment]
Strange that your payload looks different at this point as mine did where i tested it.
But it is fixed with this pull request. you just need to wait until it get merged now.

**Comment by Jawnnypoo** [comment]
Thanks for the fix @Mythen96 Should be good now @ddouglas493

**Comment by ddouglas493** [comment]
Fast Patch. I like it. ETA on a merge?

**Comment by Jawnnypoo** [comment]
@ddouglas493 It is merged now, are you still seeing the issue?

**Comment by ddouglas493** [comment]
It was working for me last night. Thanks mate!

**Comment by Jawnnypoo** [comment]
Awesome! Glad to hear it!
