### ISSUE TITLE
Update JIRA Provider

### ISSUE THREAD

**Issue by cryptic-ai** [Commit451/skyhook#144]
Quote from #39 

> Jira support is lacking a little bit.
> It just says for example that an issue has been updated, but it doesn't show what changed.
> 
> If jira sends the previous status and the new status that would be a nice addition to the messages, something similar to the emails they send:
> 
> ![image](https://user-images.githubusercontent.com/56091403/78942071-4bde6700-7a8f-11ea-832e-79f4d976857c.png)
> 
> The current messages don't show the status an issue was transitioned into.

- [ ] Verify JIRA provider and JIRA server webhook payloads
- [ ] Check to see if there are differences between Jira Server and Jira Cloud
- [ ] If there are differences, then generate a new Cloud provider.

**Comment by marth8880** [comment]
I don't know how much it will help, but I made a Jira webhook listener that posts detailed ticket change embeds. The code from that might be useful for this feature request: https://github.com/marth8880/JiraDiscordWebhooks/blob/de46b5c72f49d399fe93f73df3b7c2d776cac4fe/JiraDiscordWebhookForms/WebhookServer.cs#L380

**Comment by cryptic-ai** [comment]
I'll give it a look @marth8880!

**Comment by dscalzi** [comment]
@cryptic-ai Will you be able to get to this? If not we could probably close this as a wontfix.
