### ISSUE TITLE
Allow discord.com webhook links

### ISSUE THREAD

**Issue by andyearnshaw** [Commit451/skyhook#145]
Discord has moved to https://discord.com, and this is now the default webhook url. When you paste it into Skyhook, it's not accepted, only https://discordapp.com urls are.

**Comment by Jawnnypoo** [comment]
I don't see this as being the default webhook url. I created a new server and a new webhook and it was still `discordapp.com`

**Comment by Jawnnypoo** [comment]
Can you post a screenshot of it defaulting you to discord.com or maybe link a public server where this is the case?

**Comment by dscalzi** [comment]
The default appears to still be discordapp.com, but discord.com webhooks do work. Updated accordingly.

**Comment by Jawnnypoo** [comment]
Thanks Daniel for killing it as usual 😎

**Comment by andyearnshaw** [comment]
It might be only when you're on the web version that it's the default. If you visit https://discordapp.com, you are redirected to https://discord.com. If you choose "Open Discord" from there, you stay on discord.com, and if you go to edit any webhook to copy the URL then it gives you a discord.com URL:

<img width="487" alt="Screenshot 2020-05-14 at 10 11 25" src="https://user-images.githubusercontent.com/1826067/81916088-4c58a900-95cb-11ea-94e8-c29b928a34c5.png">

Nevertheless, thank you for the fix.
