### ISSUE TITLE
Smart Commit Error

### ISSUE THREAD

**Issue by thedevtron** [Commit451/skyhook#147]
Skyhook gives an error when pushing a commit to bitbucket that uses jira smart commit syntax to update status and add comment.

`An error has occured on skyhook for your webhook with provider jira. Maybe you can copy/paste or screenshot this error if there is no sensitive information and open an issue on the skyhook GitHub.

Error: "TypeError: Cannot read property 'fields' of undefined\n at Jira.<anonymous> (/app/dist/provider/Jira.js:46:23)\n at Generator.next (<anonymous>)\n at /app/dist/provider/Jira.js:7:71\n at new Promise (<anonymous>)\n at __awaiter (/app/dist/provider/Jira.js:3:12)\n at Jira.parseData (/app/dist/provider/Jira.js:29:16)\n at Jira.<anonymous> (/app/dist/provider/BaseProvider.js:71:33)\n at Generator.next (<anonymous>)\n at /app/dist/provider/BaseProvider.js:7:71\n at new Promise (<anonymous>)"`

**Comment by Sicdex** [comment]
all service hub is dead for skyhook (gitlab, github, and etc..)

**Comment by Jawnnypoo** [comment]
Thanks, please try skyhookapi.com instead.

**Comment by Jawnnypoo** [comment]
Closing this out, let me know if it is still broken with using https://skyhookapi.com
