### ISSUE TITLE
GitLab - Hook executed successfully but returned HTTP 403

### ISSUE THREAD

**Issue by DopeEx** [Commit451/skyhook#149]
None of my webhooks at GitLab send anything to Discord anymore. When I run a webhook test on GitLab, I get this result. The last time something was successfully submitted to Discord was on 06/03/2010 since then there have been a few events at GitLab but nothing has been received.
![gitlab](https://user-images.githubusercontent.com/16273837/86231159-63128980-bb92-11ea-8bb9-df6011de2d03.PNG)

**Comment by Jawnnypoo** [comment]
Hey there, are you using `skyhook.glitch.me`, or `skyhookapi.com`?

**Comment by DopeEx** [comment]
oh sry...i used skyhook.glitch.me and created the url now with skyhookapi.com and now everything works again Problem solved, I feel a bit stupid :D

**Comment by Jawnnypoo** [comment]
Ah, no worries! glitch has been having some weird issues lately, so we had to move away from it 👍
