### ISSUE TITLE
Gitlab to Discord: Request failed for issue events

### ISSUE THREAD

**Issue by Latecomerr** [Commit451/skyhook#151]
Push events work fine, but issue events are broken.

> Hook executed successfully but returned HTTP 502 {"message":"Request failed with status code 400","name":"Error","stack":"Error: Request failed with status code 400\n at createError (/workspace/node_modules/axios/lib/core/createError.js:16:15)\n at settle (/workspace/node_modules/axios/lib/core/settle.js:17:12)\n at IncomingMessage.handleStreamEnd (/workspace/node_modules/axios/lib/adapters/http.js:236:11)\n at IncomingMessage.emit (events.js:322:22)\n at endReadableNT (_stream_readable.js:1187:12)\n at processTicksAndRejections (internal/process/task_queues.js:84:21)","config":{"url":"[original discord webhook URL]","method":"post","data":"{\"embeds\":[{\"title\":\"undefined issue #[number] on [project name]\",\"url\":\"[link to issue]\",\"author\":{\"name\":\"[author name]\",\"icon_url\":\"[author avatar]\"},\"fields\":[{\"name\":\"[issue title]\",\"value\":\"\"}],\"footer\":{\"text\":\"Powered by Skyhook\"},\"color\":16556838}]}","headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json","User-Agent":"axios/0.19.2","Content-Length":379},"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1}}

**Comment by Jawnnypoo** [comment]
Are you using skyhookapi.com?

**Comment by Latecomerr** [comment]
> Are you using skyhookapi.com?

Yes, even doublechecked by letting the site generate the webhook URL for me.  
Like I said in the issue description, push events work fine (which would only be the case if I am using skyhookapi.com)

**Comment by jajdp** [comment]
I can confirm this. I used Discord webhooks with gitlab and Jira and both don't work anymore. 
GitLab Community Edition 13.1.1
Jira v8.10.0

**Comment by Latecomerr** [comment]
Still having the same error unfortunately

**Comment by smiziara** [comment]
I had a bad request error with VSTS and submitted a PR, the Embed Title max length on discord is 256 characters.

Can you post a full payload with the issue?
