### ISSUE TITLE
Jira webhook integration 

### ISSUE THREAD

**Issue by jajdp** [Commit451/skyhook#152]
Hello!

I used to parse my discord webhook to Jira's format by using skyhook api.
Sadly this stopped working since June 26 2020. It is now that I could get some free time to submit this issue.
Taking a look at the previous entries from Skyhook days before it stopped working completly it was showing this message on June 10.

Skyhook Error
An error has occured on skyhook for your webhook with provider jira. Maybe you can copy/paste or screenshot this error if there is no sensitive information and open an issue on the skyhook GitHub.

Error: "TypeError: Cannot read property 'fields' of undefined\n at Jira.<anonymous> (/app/dist/provider/Jira.js:46:23)\n at Generator.next (<anonymous>)\n at /app/dist/provider/Jira.js:7:71\n at new Promise (<anonymous>)\n at __awaiter (/app/dist/provider/Jira.js:3:12)\n at Jira.parseData (/app/dist/provider/Jira.js:29:16)\n at Jira.<anonymous> (/app/dist/provider/BaseProvider.js:71:33)\n at Generator.next (<anonymous>)\n at /app/dist/provider/BaseProvider.js:7:71\n at new Promise (<anonymous>)"

So...yeah.

**Comment by Advewave** [comment]
having the same issue in #157

**Comment by dscalzi** [comment]
The jira provider only supports issue and comment actions. If you disable all other triggers, does this still happen?

**Comment by jajdp** [comment]
> The jira provider only supports issue and comment actions. If you disable all other triggers, does this still happen?

Yes. It still doesn't work.
I'm trying with this configuration and it still doesn't work.

![image](https://user-images.githubusercontent.com/22821621/99887263-e51e5000-2c10-11eb-95fd-38e4e48c14ad.png)
![image](https://user-images.githubusercontent.com/22821621/99887275-f6675c80-2c10-11eb-889c-7e9827a2eac4.png)

Regards,

**Comment by dscalzi** [comment]
I'm going to setup a test JIRA and see if I can take care of these issues.

**Comment by dscalzi** [comment]
I'm not getting this issue, can you tell me exactly which action causes this to happen?

**Comment by Advewave** [comment]
> I'm not getting this issue, can you tell me exactly which action causes this to happen?

For me, it was for almost every message sent. I currently don't have a skyhook setup now, and have lost access to my previous one.

**Comment by dscalzi** [comment]
> > I'm not getting this issue, can you tell me exactly which action causes this to happen?
> 
> For me, it was for almost every message sent. I currently don't have a skyhook setup now, and have lost access to my previous one.

By that you mean creating a comment on an issue? I tried that with Jira free hosted by Atlassian, seemed to work fine. Here are some things to consider:
1. Are you self hosting? If so is the version outdated? Is it a beta version with a different payload?
2. Why is this issue happening, what payload is being sent to skyhook?
  - The best way to answer this is intercept the payload and attach it to this issue. This can easily be done using a local skyhook or something like https://requestbin.com/
3. If it is working with creating a comment on an issue, what **exact** action caused this to happen?

**Comment by jajdp** [comment]
Hi!

First of all, Thanks for taking your time to see this issue.

1. I used skyhook for parsing a Discord webhook for my Atlassian Jira (currently on version v8.12.2). I am selfhosting. As far as I know this is not a beta version.

2. I honestly don't know why is this issue happening. The message originally posted showed an error which was showing up on my Discord server days before the webhook stopped working entirely. After June 26 2020 my Discord server would not recieve any message from my Jira instance. So I don't even know what the issue is.

(I'll try to intercept the payload sent from Jira and send it here.)

3.It is not working with any configuration that I have tried up until now.

Finally, I would like to say this was working well from March up until June. For multiple triggers set on Jira. I don't know why this stopped working all of a sudden. All I can guess is, it's an update.

Thanks!

**Comment by Flash1232** [comment]
The error is happening here too. It happened to us after we had set up GitLab to automatically comment on JIRA issues mentioned in Git commits. The notification for the comment therefore seems to be the cause of the issue.

**Comment by Theinfinix500** [comment]
The error is still prompted in discord server. isnt there any workaround to prevent the error from popping out ?

**Comment by dscalzi** [comment]
> > > I'm not getting this issue, can you tell me exactly which action causes this to happen?
> > 
> > For me, it was for almost every message sent. I currently don't have a skyhook setup now, and have lost access to my previous one.
> 
> By that you mean creating a comment on an issue? I tried that with Jira free hosted by Atlassian, seemed to work fine. Here are some things to consider:
> 1. Are you self hosting? If so is the version outdated? Is it a beta version with a different payload?
> 2. Why is this issue happening, what payload is being sent to skyhook?
>   - The best way to answer this is intercept the payload and attach it to this issue. This can easily be done using a local skyhook or something like https://requestbin.com/
> 3. If it is working with creating a comment on an issue, what **exact** action caused this to happen? Are you commenting on something that is not an issue?

Ideally someone with a self hosted jira could debug the issue and tell us what's different in the payload. My above message still applies.

**Comment by zzvara** [comment]
@dscalzi,

Here is a webhook captured with `requestbin` from Atlassian JIRA v8.13.0#813000-sha1:8c68d80 running in the official Docker container pulled from `DockerHub` for the corresponding version provided earlier:

```
{
  "timestamp": 1615150687039,
  "webhookEvent": "comment_created",
  "comment": {
    "self": "https://redacted/rest/api/2/issue/17334/comment/18977",
    "id": "18977",
    "author": {
      "self": "https://redacted/rest/api/2/user?username=redacted",
      "name": "redacted",
      "key": "redacted",
      "avatarUrls": {
        "48x48": "https://redacted/secure/useravatar?ownerId=redacted&avatarId=10500",
        "24x24": "https://redacted/secure/useravatar?size=small&ownerId=redacted&avatarId=10500",
        "16x16": "https://redacted/secure/useravatar?size=xsmall&ownerId=redacted&avatarId=10500",
        "32x32": "https://redacted/secure/useravatar?size=medium&ownerId=redacted&avatarId=10500"
      },
      "displayName": "redacted",
      "active": true,
      "timeZone": "Europe/Budapest"
    },
    "body": "Test yeah.",
    "updateAuthor": {
      "self": "https://redacted/rest/api/2/user?username=redacted",
      "name": "redacted",
      "key": "redacted",
      "avatarUrls": {
        "48x48": "https://redacted/secure/useravatar?ownerId=redacted&avatarId=10500",
        "24x24": "https://redacted/secure/useravatar?size=small&ownerId=redacted&avatarId=10500",
        "16x16": "https://redacted/secure/useravatar?size=xsmall&ownerId=redacted&avatarId=10500",
        "32x32": "https://redacted/secure/useravatar?size=medium&ownerId=redacted&avatarId=10500"
      },
      "displayName": "redacted",
      "active": true,
      "timeZone": "Europe/Budapest"
    },
    "created": "2021-03-07T20:58:07.039+0000",
    "updated": "2021-03-07T20:58:07.039+0000"
  }
}
```

Could you also point us to the relevant code, so that we may be able to patch and fine-tune the Jira Server integration?

**Comment by dscalzi** [comment]
https://www.github.com/Commit451/skyhook/tree/master/src%2Fprovider%2FJira.ts

**Comment by zzvara** [comment]
@dscalzi we confirmed that this data is not in Jira's payload with version (Self-Hosted) v8.13.0. Since you confirmed that it works with the Cloud version, we should fork the implementation and create a `jira-server` provider? We could PR a version for you. What do you think?

**Comment by zzvara** [comment]
See linked issue [1].

[1] https://community.atlassian.com/t5/Jira-Software-questions/Jira-Server-v8-14-0-WebHook-missing-important-values-when-the/qaq-p/1631998#M127096

**Comment by dscalzi** [comment]
Feel free to put something together and we can review it.

**Comment by Subtixx** [comment]
For me skyhook worked until today. Now its giving me the fields error:
```
Error: "TypeError: Cannot read property 'fields' of undefined\n at Jira.<anonymous> (/app/dist/provider/Jira.js:46:23)\n at Generator.next (<anonymous>)\n at /app/dist/provider/Jira.js:7:71\n at new Promise (<anonymous>)\n at __awaiter (/app/dist/provider/Jira.js:3:12)\n at Jira.parseData (/app/dist/provider/Jira.js:29:16)\n at Jira.<anonymous> (/app/dist/provider/BaseProvider.js:71:33)\n at Generator.next (<anonymous>)\n at /app/dist/provider/BaseProvider.js:7:71\n at new Promise (<anonymous>)"
```

**Comment by zzvara** [comment]
> For me skyhook worked until today. Now its giving me the fields error:
> 
> ```
> Error: "TypeError: Cannot read property 'fields' of undefined\n at Jira.<anonymous> (/app/dist/provider/Jira.js:46:23)\n at Generator.next (<anonymous>)\n at /app/dist/provider/Jira.js:7:71\n at new Promise (<anonymous>)\n at __awaiter (/app/dist/provider/Jira.js:3:12)\n at Jira.parseData (/app/dist/provider/Jira.js:29:16)\n at Jira.<anonymous> (/app/dist/provider/BaseProvider.js:71:33)\n at Generator.next (<anonymous>)\n at /app/dist/provider/BaseProvider.js:7:71\n at new Promise (<anonymous>)"
> ```

What version are you using? And Server or Cloud?

**Comment by Subtixx** [comment]
Using JIRA Server v8.13.2#813002-sha1:c495a97)
