### ISSUE TITLE
Question about output customization

### ISSUE THREAD

**Issue by smiziara** [Commit451/skyhook#156]
Hey guys,

At my company we use Bitbucket Server and Azure Devops, both are working but we have a few needs that i would like to check if its interesting to the project that i submit some PRs:

1) Bitbucket Server with lots of reviewers became very floody on Discord, so im thinking in implementing a querystring structure to change the output of some functions a little bit. Is that okay or there's a better approach?

2) Azure Devops some messages are not great, because devops doesn't send things very cleary, gotta mix parts of some properties. There's a desired standard/layout for outputs for providers?

Thanks!

**Comment by dscalzi** [comment]
Ideally there should be a standard single output structure. If you feel like the current embed formats can be improved, we're more than happy to submit a PR. Preferably provide a sample payload so we can run some tests on it.
