### ISSUE TITLE
Skyhook Error

### ISSUE THREAD

**Issue by Advewave** [Commit451/skyhook#157]
An error has occured on skyhook for your webhook with provider jira. Maybe you can copy/paste or screenshot this error if there is no sensitive information and open an issue on the skyhook GitHub.

Error: "TypeError: Cannot read property 'fields' of undefined\n at Jira.<anonymous> (/app/dist/provider/Jira.js:46:23)\n at Generator.next (<anonymous>)\n at /app/dist/provider/Jira.js:7:71\n at new Promise (<anonymous>)\n at __awaiter (/app/dist/provider/Jira.js:3:12)\n at Jira.parseData (/app/dist/provider/Jira.js:29:16)\n at Jira.<anonymous> (/app/dist/provider/BaseProvider.js:71:33)\n at Generator.next (<anonymous>)\n at /app/dist/provider/BaseProvider.js:7:71\n at new Promise (<anonymous>)"

**Comment by gprzem** [comment]
Is it possible to hide information about error? I have all the information I need, but the bug posts are littering in the discord channel.
![image](https://user-images.githubusercontent.com/3497001/94024158-5e3b2b80-fdb7-11ea-9498-7a27b43f9991.png)

**Comment by gprzem** [comment]
Maybe some flag to disable error printing?

**Comment by dscalzi** [comment]
yea maybe, if I get some time I can look into that

**Comment by dscalzi** [comment]
Closing in favor of https://github.com/Commit451/skyhook/issues/152
