### ISSUE TITLE
Patreon: Read timed out / TypeError

### ISSUE THREAD

**Issue by gregzaal** [Commit451/skyhook#161]
Patreon hooks are not working. Sending any of the test requests (for any event) results in this error:

```
Test Response
---
Error: _HTTPSConnectionPool(host='skyhookapi.com', port=443): Read timed out. (read timeout=10)
```

If I enable the events anyway, then this message shows up in discord 3 times before patreon automatically disables the hook:

> Skyhook Error
> An error has occured on skyhook for your webhook with provider patreon. Maybe you can copy/paste or screenshot this error if there is no sensitive information and open an issue on the skyhook GitHub.
> 
> Error: "TypeError: Reduce of empty array with no initial value\n at Array.reduce (<anonymous>)\n at Patreon._handleAPIV2 (/app/dist/provider/Patreon.js:90:14)\n at Patreon.<anonymous> (/app/dist/provider/Patreon.js:121:18)\n at Generator.next (<anonymous>)\n at /app/dist/provider/Patreon.js:7:71\n at new Promise (<anonymous>)\n at __awaiter (/app/dist/provider/Patreon.js:3:12)\n at Patreon.membersCreate (/app/dist/provider/Patreon.js:120:16)\n at Patreon.<anonymous> (/app/dist/provider/BaseProvider.js:71:33)\n at Generator.next (<anonymous>)"

**Comment by gregzaal** [comment]
Thanks ❤️ Is this fix deployed? I'm still getting the same error when testing the hook.

**Comment by dscalzi** [comment]
Probably not deployed yet, I'll let you know when it goes live.

**Comment by dscalzi** [comment]
> Thanks ❤️ Is this fix deployed? I'm still getting the same error when testing the hook.

Deployed

**Comment by gregzaal** [comment]
I'm still getting the same error, both when testing and in discord itself. I notice copy pasting the message here initially, github removed some `<anonymous>` tags, maybe that's relevant. So here's the error with better formatting:

```js
TypeError: Reduce of empty array with no initial value
 at Array.reduce (<anonymous>)
 at Patreon._handleAPIV2 (/workspace/dist/provider/Patreon.js:90:14)
 at Patreon.<anonymous> (/workspace/dist/provider/Patreon.js:121:18)
 at Generator.next (<anonymous>)
 at /workspace/dist/provider/Patreon.js:7:71
 at new Promise (<anonymous>)
 at __awaiter (/workspace/dist/provider/Patreon.js:3:12)
 at Patreon.membersCreate (/workspace/dist/provider/Patreon.js:120:16)
 at Patreon.<anonymous> (/workspace/dist/provider/BaseProvider.js:71:33)
 at Generator.next (<anonymous>)```

**Comment by dscalzi** [comment]
That doesn't seem right because the call to reduce is on line 91 when I compile what's on master.

@Jawnnypoo any thoughts?

**Comment by Jawnnypoo** [comment]
Are you looking at the `.ts` file or the generated `.js` file? The lines will be different.

**Comment by dscalzi** [comment]
I'm looking at the js file

**Comment by dscalzi** [comment]
It's also not possible for this to happen, the fix adds a check that the array's length is > 0 before attempting a reduction. So an empty array cannot be operated on.

**Comment by Jawnnypoo** [comment]
Yes, this could very well be possible. Let me deploy again

**Comment by Jawnnypoo** [comment]
Yeah I think I forgot to build before redeploying. Sorry about that. Should be fixed now!
