### ISSUE TITLE
Heroku release showing undefined for app name

### ISSUE THREAD

**Issue by theprivileges** [Commit451/skyhook#173]
Current implementation of Heroku provider handles an outdated payload, and does not display the correct app name on the message that gets displayed on Discord. 

https://github.com/Commit451/skyhook/blob/db375fc13eb1b1d00ff7b7027616e50a240bf001/src/provider/Heroku.ts#L21

**Current Message**
<img width="406" alt="Captura_de_Tela_2021-04-14_às_17_11_53" src="https://user-images.githubusercontent.com/844516/114791955-a36b7e80-9d44-11eb-9f63-6c2cabc50a44.png">

**Example payload**

![image](https://user-images.githubusercontent.com/844516/114791820-61423d00-9d44-11eb-8210-118707027702.png)

**Desired outcome**

The `name` is extracted from `data.app.name`, and the message sent to Discord includes the correct name of the app.

**Comment by Jawnnypoo** [comment]
Thanks, fixed now!
