### ISSUE TITLE
App Center support

### ISSUE THREAD

**Issue by vskliam** [Commit451/skyhook#179]
Hey! Big thanks for your project! I've already integrated Bitbucket webhooks.

Can you please add support for App Center?

https://docs.microsoft.com/en-us/appcenter/dashboard/webhooks/

Also, there was a direct support request to the App Center team, I think you can find some useful information there:

https://github.com/microsoft/appcenter/issues/1862

**Comment by TiagoDanin** [comment]
I'm working on it

**Comment by TiagoDanin** [comment]
MR #203
