### ISSUE TITLE
BitBucket rejected event of 'Pull Request: Request Change' with 502.

### ISSUE THREAD

**Issue by LuviKunG** [Commit451/skyhook#189]
I've check that Skyhook still didn't support for this two events.

- pullrequest:changes_request_created
- pullrequest:changes_request_removed

That's making BitBucket shows error code 502.

```json
{"message":"Request failed with status code 400","name":"Error","stack":"Error: Request failed with status code 400\n    at createError (/rbd/pnpm-volume/90fb9114-add2-4467-b406-16062c42fe85/node_modules/.registry.npmjs.org/axios/0.19.2/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/rbd/pnpm-volume/90fb9114-add2-4467-b406-16062c42fe85/node_modules/.registry.npmjs.org/axios/0.19.2/node_modules/axios/lib/core/settle.js:17:12)\n    at IncomingMessage.handleStreamEnd (/rbd/pnpm-volume/90fb9114-add2-4467-b406-16062c42fe85/node_modules/.registry.npmjs.org/axios/0.19.2/node_modules/axios/lib/adapters/http.js:236:11)\n    at IncomingMessage.emit (events.js:201:15)\n    at endReadableNT (_stream_readable.js:1130:12)\n    at processTicksAndRejections (internal/process/task_queues.js:83:17)"}
```

**Comment by BetterB0y** [comment]
I have similar issue
Here's my respose:

`{"message":"Request failed with status code 404","name":"AxiosError","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"env":{},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json","User-Agent":"axios/0.27.2","Content-Length":516},"data":"{\"embeds\":[{\"author\":{\"name\":\"Daniel Pakosz\",\"icon_url\":\"https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/62134b469cd4a70071dd3bf4/6137cf02-16f6-4bc0-9794-48002e192735/128\",\"url\":\"https://bitbucket.org/undefined\"},\"title\":\"[better_boy/test] Updated pull request: #4 test\",\"url\":\"https://bitbucket.org/better_boy/test/pull-requests/4\",\"description\":\"\",\"fields\":[{\"name\":\"test\",\"value\":\"**Destination branch:** master\\n**State:** OPEN\\n\"}],\"footer\":{\"text\":\"Powered by Skyhook\"},\"color\":2117761}]}","method":"post","url":"https://discordapp.com/api/webhooks/971716019078959155/1G8ZhZBBjdhuGsBm7nAaX51Um8oQ7dF0zGfqRDiVYCclul0R1ymmJaLMPf0dzQBw-MGm"},"code":"ERR_BAD_REQUEST","status":404}
`

**Comment by BetterB0y** [comment]
Something changed. Now I got status 200 and body
`Webhook event is either not supported or not implemented by /bitbucket.`

**Comment by Jawnnypoo** [comment]
Do you know what kind of event this is happening on?

**Comment by BetterB0y** [comment]
Its happening with request changes in PR

**Comment by Jawnnypoo** [comment]
Hmmm yeah so that event is probably not supported. Can you get a JSON example of what the event looks like?

**Comment by BetterB0y** [comment]
Here you go
`{
  "changes_request": {
    "date": "2022-05-22T13:19:03.260699+00:00",
    "user": {
      "display_name": "Daniel Pakosz",
      "uuid": "{1fef5fec-1660-40e2-ac86-735082b94b74}",
      "links": {
        "self": {
          "href": "https://api.bitbucket.org/2.0/users/%7B1fef5fec-1660-40e2-ac86-735082b94b74%7D"
        },
        "html": {
          "href": "https://bitbucket.org/%7B1fef5fec-1660-40e2-ac86-735082b94b74%7D/"
        },
        "avatar": {
          "href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/61b7484a2960d200695b2d9f/436597e5-28d5-4078-bdfa-29b1598e582c/128"
        }
      },
      "type": "user",
      "nickname": "Daniel Pakosz",
      "account_id": "61b7484a2960d200695b2d9f"
    }
  },
  "pullrequest": {
    "rendered": {
      "description": {
        "raw": "tesrdas created online with Bitbucket",
        "markup": "markdown",
        "html": "<p>tesrdas created online with Bitbucket</p>",
        "type": "rendered"
      },
      "title": {
        "raw": "tesrdas created online with Bitbucket",
        "markup": "markdown",
        "html": "<p>tesrdas created online with Bitbucket</p>",
        "type": "rendered"
      }
    },
    "type": "pullrequest",
    "description": "tesrdas created online with Bitbucket",
    "links": {
      "decline": {
        "href": "https://api.bitbucket.org/2.0/repositories/better_boy/test/pullrequests/5/decline"
      },
      "diffstat": {
        "href": "https://api.bitbucket.org/2.0/repositories/better_boy/test/diffstat/better_boy/test:30152af281d3%0D188d49fe68de?from_pullrequest_id=5"
      },
      "commits": {
        "href": "https://api.bitbucket.org/2.0/repositories/better_boy/test/pullrequests/5/commits"
      },
      "self": {
        "href": "https://api.bitbucket.org/2.0/repositories/better_boy/test/pullrequests/5"
      },
      "comments": {
        "href": "https://api.bitbucket.org/2.0/repositories/better_boy/test/pullrequests/5/comments"
      },
      "merge": {
        "href": "https://api.bitbucket.org/2.0/repositories/better_boy/test/pullrequests/5/merge"
      },
      "html": {
        "href": "https://bitbucket.org/better_boy/test/pull-requests/5"
      },
      "activity": {
        "href": "https://api.bitbucket.org/2.0/repositories/better_boy/test/pullrequests/5/activity"
      },
      "request-changes": {
        "href": "https://api.bitbucket.org/2.0/repositories/better_boy/test/pullrequests/5/request-changes"
      },
      "diff": {
        "href": "https://api.bitbucket.org/2.0/repositories/better_boy/test/diff/better_boy/test:30152af281d3%0D188d49fe68de?from_pullrequest_id=5"
      },
      "approve": {
        "href": "https://api.bitbucket.org/2.0/repositories/better_boy/test/pullrequests/5/approve"
      },
      "statuses": {
        "href": "https://api.bitbucket.org/2.0/repositories/better_boy/test/pullrequests/5/statuses"
      }
    },
    "title": "tesrdas created online with Bitbucket",
    "close_source_branch": true,
    "reviewers": [
      {
        "display_name": "Daniel Pakosz",
        "uuid": "{1fef5fec-1660-40e2-ac86-735082b94b74}",
        "links": {
          "self": {
            "href": "https://api.bitbucket.org/2.0/users/%7B1fef5fec-1660-40e2-ac86-735082b94b74%7D"
          },
          "html": {
            "href": "https://bitbucket.org/%7B1fef5fec-1660-40e2-ac86-735082b94b74%7D/"
          },
          "avatar": {
            "href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/61b7484a2960d200695b2d9f/436597e5-28d5-4078-bdfa-29b1598e582c/128"
          }
        },
        "type": "user",
        "nickname": "Daniel Pakosz",
        "account_id": "61b7484a2960d200695b2d9f"
      }
    ],
    "id": 5,
    "destination": {
      "commit": {
        "hash": "188d49fe68de",
        "type": "commit",
        "links": {
          "self": {
            "href": "https://api.bitbucket.org/2.0/repositories/better_boy/test/commit/188d49fe68de"
          },
          "html": {
            "href": "https://bitbucket.org/better_boy/test/commits/188d49fe68de"
          }
        }
      },
      "repository": {
        "links": {
          "self": {
            "href": "https://api.bitbucket.org/2.0/repositories/better_boy/test"
          },
          "html": {
            "href": "https://bitbucket.org/better_boy/test"
          },
          "avatar": {
            "href": "https://bytebucket.org/ravatar/%7B824403ee-a646-47db-838d-8fb67ff8b025%7D?ts=default"
          }
        },
        "type": "repository",
        "name": "test",
        "full_name": "better_boy/test",
        "uuid": "{824403ee-a646-47db-838d-8fb67ff8b025}"
      },
      "branch": {
        "name": "toTesting"
      }
    },
    "created_on": "2022-05-22T13:04:40.672914+00:00",
    "summary": {
      "raw": "tesrdas created online with Bitbucket",
      "markup": "markdown",
      "html": "<p>tesrdas created online with Bitbucket</p>",
      "type": "rendered"
    },
    "source": {
      "commit": {
        "hash": "30152af281d3",
        "type": "commit",
        "links": {
          "self": {
            "href": "https://api.bitbucket.org/2.0/repositories/better_boy/test/commit/30152af281d3"
          },
          "html": {
            "href": "https://bitbucket.org/better_boy/test/commits/30152af281d3"
          }
        }
      },
      "repository": {
        "links": {
          "self": {
            "href": "https://api.bitbucket.org/2.0/repositories/better_boy/test"
          },
          "html": {
            "href": "https://bitbucket.org/better_boy/test"
          },
          "avatar": {
            "href": "https://bytebucket.org/ravatar/%7B824403ee-a646-47db-838d-8fb67ff8b025%7D?ts=default"
          }
        },
        "type": "repository",
        "name": "test",
        "full_name": "better_boy/test",
        "uuid": "{824403ee-a646-47db-838d-8fb67ff8b025}"
      },
      "branch": {
        "name": "Daniel-Pakosz/tesrdas-created-online-with-bitbucket-1653224673897"
      }
    },
    "comment_count": 0,
    "state": "OPEN",
    "task_count": 0,
    "participants": [
      {
        "participated_on": "2022-05-22T13:19:03.260699+00:00",
        "state": "changes_requested",
        "role": "REVIEWER",
        "user": {
          "display_name": "Daniel Pakosz",
          "uuid": "{1fef5fec-1660-40e2-ac86-735082b94b74}",
          "links": {
            "self": {
              "href": "https://api.bitbucket.org/2.0/users/%7B1fef5fec-1660-40e2-ac86-735082b94b74%7D"
            },
            "html": {
              "href": "https://bitbucket.org/%7B1fef5fec-1660-40e2-ac86-735082b94b74%7D/"
            },
            "avatar": {
              "href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/61b7484a2960d200695b2d9f/436597e5-28d5-4078-bdfa-29b1598e582c/128"
            }
          },
          "type": "user",
          "nickname": "Daniel Pakosz",
          "account_id": "61b7484a2960d200695b2d9f"
        },
        "type": "participant",
        "approved": false
      }
    ],
    "reason": "",
    "updated_on": "2022-05-22T13:19:01.744076+00:00",
    "author": {
      "display_name": "Daniel Pakosz",
      "uuid": "{77ab6177-c1b4-4c19-a0a8-3812ec6d92ef}",
      "links": {
        "self": {
          "href": "https://api.bitbucket.org/2.0/users/%7B77ab6177-c1b4-4c19-a0a8-3812ec6d92ef%7D"
        },
        "html": {
          "href": "https://bitbucket.org/%7B77ab6177-c1b4-4c19-a0a8-3812ec6d92ef%7D/"
        },
        "avatar": {
          "href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/62134b469cd4a70071dd3bf4/6137cf02-16f6-4bc0-9794-48002e192735/128"
        }
      },
      "type": "user",
      "nickname": "Daniel Pakosz",
      "account_id": "62134b469cd4a70071dd3bf4"
    },
    "merge_commit": null,
    "closed_by": null
  },
  "repository": {
    "scm": "git",
    "website": null,
    "uuid": "{824403ee-a646-47db-838d-8fb67ff8b025}",
    "links": {
      "self": {
        "href": "https://api.bitbucket.org/2.0/repositories/better_boy/test"
      },
      "html": {
        "href": "https://bitbucket.org/better_boy/test"
      },
      "avatar": {
        "href": "https://bytebucket.org/ravatar/%7B824403ee-a646-47db-838d-8fb67ff8b025%7D?ts=default"
      }
    },
    "project": {
      "links": {
        "self": {
          "href": "https://api.bitbucket.org/2.0/workspaces/better_boy/projects/TEST"
        },
        "html": {
          "href": "https://bitbucket.org/better_boy/workspace/projects/TEST"
        },
        "avatar": {
          "href": "https://bitbucket.org/account/user/better_boy/projects/TEST/avatar/32?ts=1647289871"
        }
      },
      "type": "project",
      "name": "test",
      "key": "TEST",
      "uuid": "{a7c00b0e-4435-447e-8788-dfbee925de90}"
    },
    "full_name": "better_boy/test",
    "owner": {
      "display_name": "Daniel Pakosz",
      "uuid": "{1fef5fec-1660-40e2-ac86-735082b94b74}",
      "links": {
        "self": {
          "href": "https://api.bitbucket.org/2.0/users/%7B1fef5fec-1660-40e2-ac86-735082b94b74%7D"
        },
        "html": {
          "href": "https://bitbucket.org/%7B1fef5fec-1660-40e2-ac86-735082b94b74%7D/"
        },
        "avatar": {
          "href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/61b7484a2960d200695b2d9f/436597e5-28d5-4078-bdfa-29b1598e582c/128"
        }
      },
      "type": "user",
      "nickname": "Daniel Pakosz",
      "account_id": "61b7484a2960d200695b2d9f"
    },
    "workspace": {
      "slug": "better_boy",
      "type": "workspace",
      "name": "Daniel Pakosz",
      "links": {
        "self": {
          "href": "https://api.bitbucket.org/2.0/workspaces/better_boy"
        },
        "html": {
          "href": "https://bitbucket.org/better_boy/"
        },
        "avatar": {
          "href": "https://bitbucket.org/workspaces/better_boy/avatar/?ts=1645430992"
        }
      },
      "uuid": "{1fef5fec-1660-40e2-ac86-735082b94b74}"
    },
    "type": "repository",
    "is_private": true,
    "name": "test"
  },
  "actor": {
    "display_name": "Daniel Pakosz",
    "uuid": "{1fef5fec-1660-40e2-ac86-735082b94b74}",
    "links": {
      "self": {
        "href": "https://api.bitbucket.org/2.0/users/%7B1fef5fec-1660-40e2-ac86-735082b94b74%7D"
      },
      "html": {
        "href": "https://bitbucket.org/%7B1fef5fec-1660-40e2-ac86-735082b94b74%7D/"
      },
      "avatar": {
        "href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/61b7484a2960d200695b2d9f/436597e5-28d5-4078-bdfa-29b1598e582c/128"
      }
    },
    "type": "user",
    "nickname": "Daniel Pakosz",
    "account_id": "61b7484a2960d200695b2d9f"
  }
}`

**Comment by BetterB0y** [comment]
Here is
pullrequest:changes_request_removed
which author of issue mentioned.
{
  "changes_request": {
    "date": "2022-05-22T13:19:03.260699+00:00",
    "user": {
      "display_name": "Daniel Pakosz",
      "uuid": "{1fef5fec-1660-40e2-ac86-735082b94b74}",
      "links": {
        "self": {
          "href": "https://api.bitbucket.org/2.0/users/%7B1fef5fec-1660-40e2-ac86-735082b94b74%7D"
        },
        "html": {
          "href": "https://bitbucket.org/%7B1fef5fec-1660-40e2-ac86-735082b94b74%7D/"
        },
        "avatar": {
          "href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/61b7484a2960d200695b2d9f/436597e5-28d5-4078-bdfa-29b1598e582c/128"
        }
      },
      "type": "user",
      "nickname": "Daniel Pakosz",
      "account_id": "61b7484a2960d200695b2d9f"
    }
  },
  "pullrequest": {
    "rendered": {
      "description": {
        "raw": "tesrdas created online with Bitbucket",
        "markup": "markdown",
        "html": "<p>tesrdas created online with Bitbucket</p>",
        "type": "rendered"
      },
      "title": {
        "raw": "tesrdas created online with Bitbucket",
        "markup": "markdown",
        "html": "<p>tesrdas created online with Bitbucket</p>",
        "type": "rendered"
      }
    },
    "type": "pullrequest",
    "description": "tesrdas created online with Bitbucket",
    "links": {
      "decline": {
        "href": "https://api.bitbucket.org/2.0/repositories/better_boy/test/pullrequests/5/decline"
      },
      "diffstat": {
        "href": "https://api.bitbucket.org/2.0/repositories/better_boy/test/diffstat/better_boy/test:30152af281d3%0D188d49fe68de?from_pullrequest_id=5"
      },
      "commits": {
        "href": "https://api.bitbucket.org/2.0/repositories/better_boy/test/pullrequests/5/commits"
      },
      "self": {
        "href": "https://api.bitbucket.org/2.0/repositories/better_boy/test/pullrequests/5"
      },
      "comments": {
        "href": "https://api.bitbucket.org/2.0/repositories/better_boy/test/pullrequests/5/comments"
      },
      "merge": {
        "href": "https://api.bitbucket.org/2.0/repositories/better_boy/test/pullrequests/5/merge"
      },
      "html": {
        "href": "https://bitbucket.org/better_boy/test/pull-requests/5"
      },
      "activity": {
        "href": "https://api.bitbucket.org/2.0/repositories/better_boy/test/pullrequests/5/activity"
      },
      "request-changes": {
        "href": "https://api.bitbucket.org/2.0/repositories/better_boy/test/pullrequests/5/request-changes"
      },
      "diff": {
        "href": "https://api.bitbucket.org/2.0/repositories/better_boy/test/diff/better_boy/test:30152af281d3%0D188d49fe68de?from_pullrequest_id=5"
      },
      "approve": {
        "href": "https://api.bitbucket.org/2.0/repositories/better_boy/test/pullrequests/5/approve"
      },
      "statuses": {
        "href": "https://api.bitbucket.org/2.0/repositories/better_boy/test/pullrequests/5/statuses"
      }
    },
    "title": "tesrdas created online with Bitbucket",
    "close_source_branch": true,
    "reviewers": [
      {
        "display_name": "Daniel Pakosz",
        "uuid": "{1fef5fec-1660-40e2-ac86-735082b94b74}",
        "links": {
          "self": {
            "href": "https://api.bitbucket.org/2.0/users/%7B1fef5fec-1660-40e2-ac86-735082b94b74%7D"
          },
          "html": {
            "href": "https://bitbucket.org/%7B1fef5fec-1660-40e2-ac86-735082b94b74%7D/"
          },
          "avatar": {
            "href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/61b7484a2960d200695b2d9f/436597e5-28d5-4078-bdfa-29b1598e582c/128"
          }
        },
        "type": "user",
        "nickname": "Daniel Pakosz",
        "account_id": "61b7484a2960d200695b2d9f"
      }
    ],
    "id": 5,
    "destination": {
      "commit": {
        "hash": "188d49fe68de",
        "type": "commit",
        "links": {
          "self": {
            "href": "https://api.bitbucket.org/2.0/repositories/better_boy/test/commit/188d49fe68de"
          },
          "html": {
            "href": "https://bitbucket.org/better_boy/test/commits/188d49fe68de"
          }
        }
      },
      "repository": {
        "links": {
          "self": {
            "href": "https://api.bitbucket.org/2.0/repositories/better_boy/test"
          },
          "html": {
            "href": "https://bitbucket.org/better_boy/test"
          },
          "avatar": {
            "href": "https://bytebucket.org/ravatar/%7B824403ee-a646-47db-838d-8fb67ff8b025%7D?ts=default"
          }
        },
        "type": "repository",
        "name": "test",
        "full_name": "better_boy/test",
        "uuid": "{824403ee-a646-47db-838d-8fb67ff8b025}"
      },
      "branch": {
        "name": "toTesting"
      }
    },
    "created_on": "2022-05-22T13:04:40.672914+00:00",
    "summary": {
      "raw": "tesrdas created online with Bitbucket",
      "markup": "markdown",
      "html": "<p>tesrdas created online with Bitbucket</p>",
      "type": "rendered"
    },
    "source": {
      "commit": {
        "hash": "30152af281d3",
        "type": "commit",
        "links": {
          "self": {
            "href": "https://api.bitbucket.org/2.0/repositories/better_boy/test/commit/30152af281d3"
          },
          "html": {
            "href": "https://bitbucket.org/better_boy/test/commits/30152af281d3"
          }
        }
      },
      "repository": {
        "links": {
          "self": {
            "href": "https://api.bitbucket.org/2.0/repositories/better_boy/test"
          },
          "html": {
            "href": "https://bitbucket.org/better_boy/test"
          },
          "avatar": {
            "href": "https://bytebucket.org/ravatar/%7B824403ee-a646-47db-838d-8fb67ff8b025%7D?ts=default"
          }
        },
        "type": "repository",
        "name": "test",
        "full_name": "better_boy/test",
        "uuid": "{824403ee-a646-47db-838d-8fb67ff8b025}"
      },
      "branch": {
        "name": "Daniel-Pakosz/tesrdas-created-online-with-bitbucket-1653224673897"
      }
    },
    "comment_count": 0,
    "state": "OPEN",
    "task_count": 0,
    "participants": [
      {
        "participated_on": null,
        "state": null,
        "role": "REVIEWER",
        "user": {
          "display_name": "Daniel Pakosz",
          "uuid": "{1fef5fec-1660-40e2-ac86-735082b94b74}",
          "links": {
            "self": {
              "href": "https://api.bitbucket.org/2.0/users/%7B1fef5fec-1660-40e2-ac86-735082b94b74%7D"
            },
            "html": {
              "href": "https://bitbucket.org/%7B1fef5fec-1660-40e2-ac86-735082b94b74%7D/"
            },
            "avatar": {
              "href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/61b7484a2960d200695b2d9f/436597e5-28d5-4078-bdfa-29b1598e582c/128"
            }
          },
          "type": "user",
          "nickname": "Daniel Pakosz",
          "account_id": "61b7484a2960d200695b2d9f"
        },
        "type": "participant",
        "approved": false
      }
    ],
    "reason": "",
    "updated_on": "2022-05-23T21:11:07.560773+00:00",
    "author": {
      "display_name": "Daniel Pakosz",
      "uuid": "{77ab6177-c1b4-4c19-a0a8-3812ec6d92ef}",
      "links": {
        "self": {
          "href": "https://api.bitbucket.org/2.0/users/%7B77ab6177-c1b4-4c19-a0a8-3812ec6d92ef%7D"
        },
        "html": {
          "href": "https://bitbucket.org/%7B77ab6177-c1b4-4c19-a0a8-3812ec6d92ef%7D/"
        },
        "avatar": {
          "href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/62134b469cd4a70071dd3bf4/6137cf02-16f6-4bc0-9794-48002e192735/128"
        }
      },
      "type": "user",
      "nickname": "Daniel Pakosz",
      "account_id": "62134b469cd4a70071dd3bf4"
    },
    "merge_commit": null,
    "closed_by": null
  },
  "repository": {
    "scm": "git",
    "website": null,
    "uuid": "{824403ee-a646-47db-838d-8fb67ff8b025}",
    "links": {
      "self": {
        "href": "https://api.bitbucket.org/2.0/repositories/better_boy/test"
      },
      "html": {
        "href": "https://bitbucket.org/better_boy/test"
      },
      "avatar": {
        "href": "https://bytebucket.org/ravatar/%7B824403ee-a646-47db-838d-8fb67ff8b025%7D?ts=default"
      }
    },
    "project": {
      "links": {
        "self": {
          "href": "https://api.bitbucket.org/2.0/workspaces/better_boy/projects/TEST"
        },
        "html": {
          "href": "https://bitbucket.org/better_boy/workspace/projects/TEST"
        },
        "avatar": {
          "href": "https://bitbucket.org/account/user/better_boy/projects/TEST/avatar/32?ts=1647289871"
        }
      },
      "type": "project",
      "name": "test",
      "key": "TEST",
      "uuid": "{a7c00b0e-4435-447e-8788-dfbee925de90}"
    },
    "full_name": "better_boy/test",
    "owner": {
      "display_name": "Daniel Pakosz",
      "uuid": "{1fef5fec-1660-40e2-ac86-735082b94b74}",
      "links": {
        "self": {
          "href": "https://api.bitbucket.org/2.0/users/%7B1fef5fec-1660-40e2-ac86-735082b94b74%7D"
        },
        "html": {
          "href": "https://bitbucket.org/%7B1fef5fec-1660-40e2-ac86-735082b94b74%7D/"
        },
        "avatar": {
          "href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/61b7484a2960d200695b2d9f/436597e5-28d5-4078-bdfa-29b1598e582c/128"
        }
      },
      "type": "user",
      "nickname": "Daniel Pakosz",
      "account_id": "61b7484a2960d200695b2d9f"
    },
    "workspace": {
      "slug": "better_boy",
      "type": "workspace",
      "name": "Daniel Pakosz",
      "links": {
        "self": {
          "href": "https://api.bitbucket.org/2.0/workspaces/better_boy"
        },
        "html": {
          "href": "https://bitbucket.org/better_boy/"
        },
        "avatar": {
          "href": "https://bitbucket.org/workspaces/better_boy/avatar/?ts=1645430992"
        }
      },
      "uuid": "{1fef5fec-1660-40e2-ac86-735082b94b74}"
    },
    "type": "repository",
    "is_private": true,
    "name": "test"
  },
  "actor": {
    "display_name": "Daniel Pakosz",
    "uuid": "{1fef5fec-1660-40e2-ac86-735082b94b74}",
    "links": {
      "self": {
        "href": "https://api.bitbucket.org/2.0/users/%7B1fef5fec-1660-40e2-ac86-735082b94b74%7D"
      },
      "html": {
        "href": "https://bitbucket.org/%7B1fef5fec-1660-40e2-ac86-735082b94b74%7D/"
      },
      "avatar": {
        "href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/61b7484a2960d200695b2d9f/436597e5-28d5-4078-bdfa-29b1598e582c/128"
      }
    },
    "type": "user",
    "nickname": "Daniel Pakosz",
    "account_id": "61b7484a2960d200695b2d9f"
  }
}
