### ISSUE TITLE
Add New Relic support

### ISSUE THREAD

**Issue by markhaehnel** [Commit451/skyhook#19]
Would be great to have Webhook translation from New Relic to Discord!

**Comment by Mythen96** [comment]
Can you please provide us a url to the service website ?

**Comment by Jawnnypoo** [comment]
This is what I have found:

https://docs.newrelic.com/docs/alerts/new-relic-alerts/managing-notification-channels/customize-your-webhook-payload

Is that what you are referring to @EZTEQ ?

**Comment by EZTEQ** [comment]
Yep, that's it.

**Comment by Jawnnypoo** [comment]
True, I did not add a test or add it to the webpage though, we would still need to do that.

**Comment by Jawnnypoo** [comment]
It's live now. I didn't really know what information is relevant since I do not use New Relic, so I am open to suggestions or PRs adjusting the style!
