### ISSUE TITLE
Pingdom check name not included in discord

### ISSUE THREAD

**Issue by Einarsson** [Commit451/skyhook#191]
According to the code, the title of the message should be:

```
title: this.body.check_name + ' - State changed',
```

but the discord message looks like this:
![image](https://user-images.githubusercontent.com/526098/152372974-f6f8c9a2-35de-4149-9887-96f9d233e367.png)

**Comment by Einarsson** [comment]
Update: It runs in local, you just need to redeploy last version. :)

**Comment by Einarsson** [comment]
Seems to be working now. Thank you!

**Comment by Jawnnypoo** [comment]
Yep, deployed last night. Thanks!
