### ISSUE TITLE
Gitlab: Branch Name Cut Off

### ISSUE THREAD

**Issue by KuroThing** [Commit451/skyhook#20]
If the branch name is something like `Features/SomeFeature`,  the branch is only "Features".

Possible solution: Skip the first 1/2 elements of the array then rejoin everything using `/` again [here](https://github.com/Commit451/skyhook/blob/master/providers/gitlab.js#L18)

**Comment by Jawnnypoo** [comment]
Fixed thanks to @Mythen96

**Comment by KuroThing** [comment]
Thanks.
