### ISSUE TITLE
No length guards

### ISSUE THREAD

**Issue by KuroThing** [Commit451/skyhook#22]
It appears that none of the embeds have any length guards against exceeding the maximum size of Discords Embeds / messages.

Limits are...
* 25 Fields
  * Name: 256
  * Value: 1024
* Description: 2048
* Total Length: 4000

I believe i accidentally exceed the description limit with a merge...

**Comment by Mythen96** [comment]
i will check that and build that in later this day. I already read that too but didnt thought about that where i moved the source to use embeds.
Thanks for reminding me!

**Comment by Mythen96** [comment]
So my pull request should fix that it exceeds the maximum of discord embeds(total length of 6000 is allowed).
