### ISSUE TITLE
Jenkins CI Support

### ISSUE THREAD

**Issue by tmfksoft** [Commit451/skyhook#24]
I use Jenkins extensively for compiling my public PaperMC/Spigot plugins.

I'd like to have messages forwarded to my Discord so plugin users can see when a new release or patch is out.

Although I don't believe that Jenkins has built in functionality there is a plugin meant for the job:
https://wiki.jenkins-ci.org/display/JENKINS/Notification+Plugin

The plugin page shows the format of the data.
The IRC bot for example uses the following message format:

Project SomeProject build #123: SUCCESS in 2 min 10 sec: https://ci.example.com/job/AProject/123/

Where SUCCESS can be any of the results.

**Comment by Mythen96** [comment]
As soon as i'm at home i will have a look into it

**Comment by Jawnnypoo** [comment]
Should work now! 👍 Props to @Mythen96
