### ISSUE TITLE
Commit from Unknown

### ISSUE THREAD

**Issue by ddouglas493** [Commit451/skyhook#27]
Just recently, this message started appearing instead of my name above my commit. 

http://i.imgur.com/aRYERZS.png

Let me know you need to track this

**Comment by Jawnnypoo** [comment]
@Mythen96 Any ideas what may have changed here?

**Comment by Mythen96** [comment]
"Commit from Unknown" is shown when the commits itself doesnt have a valid User attribute in their payload data.
As reference i can only show this:
[providers/bitbucket.js#37](https://github.com/Commit451/skyhook/blob/ab764face74216d356c6e38ab1f062d80c677508/providers/bitbucket.js#L37)

On my end it still works fine.

**Comment by ddouglas493** [comment]
@Mythen96 I examined one of the raw commits coming into Bitbucket. Below is the Header of the Commit. The author is set correctly.

```
From de8818094eaa283e7f85ebeda671651e297529ea Mon Sep 17 00:00:00 2001
From: David Douglas <admin@evemail.space>
Date: Thu, 15 Jun 2017 05:02:54 +0000
Subject: [PATCH] Added Logging to Middleware to see when somebody accesses a
 page and if they were denied

---
```

**Comment by ddouglas493** [comment]
I just confirmed with another commit, everything going into Bitbucket is correct. This must have something to do with the hook leave Bitbucket and going to Skyhook.

**Comment by Mythen96** [comment]
i would need a complete body of a request that is going to skyhook and not just only the headers as we dont work with the headers.
And yes the global author is set correctly thats even seen at the discord messages. But BitBucket sends author information in every commit to know when a commit comes from a different user.

**Comment by ddouglas493** [comment]
I am looking at the body right now. I think I found the issue. 

https://github.com/Commit451/skyhook/blob/ab764face74216d356c6e38ab1f062d80c677508/providers/bitbucket.js#L37

As you outlined here, you are looking for the key **commit.author.user** but, and I maybe completely wrong, according to the request body from Bitbucket, this key should read **commit. author. raw**

Here is the Gist
https://gist.github.com/ddouglas493/f36c7e81e73b999f52efbc62581c26c5#file-requestbody-json-L31

**Comment by Mythen96** [comment]
Nope, the key you referred is the key for the global user. As you can see in the commit section of your gist, every commit has its own user property:
https://gist.github.com/ddouglas493/f36c7e81e73b999f52efbc62581c26c5#file-requestbody-json-L91

That is used for the commits. And it seems like BitBucket sends only raw author information that we dont use. The problem here is probably that bitbucket doesnt recognize with which user you are pushing the commits and as that cant send the user information.
How it should look like in the author section:
https://gist.github.com/Mythen96/543c76b61fb5871152e0f25213e43618#file-bitbucket_push_event-json-L108

**Comment by Mythen96** [comment]
The thing why i made the fallback to "Unknown" instead of the Raw format that BitBucket is providing ("User Name <email>") is that i think that most users dont want their email to be public.

**Comment by ddouglas493** [comment]
I believe this is on my end. This did not start until I start pushing the individual branches. I will do some experimenting on my end and see if I can figure out what causes the Author property to be so bare.

**Comment by ddouglas493** [comment]
I have no clue if this is **THE** for this issue, but I did notice that this entire time the email address was outdated. From an old project, so I updated it. Now the Author property is formatted correctly

https://gist.github.com/ddouglas493/45771104bcc70c78559d16fb3f1ee1a4#file-bitbucket-json-L91

**Comment by Jawnnypoo** [comment]
Glad this was resolved! 👍
