### ISSUE TITLE
Cannot GET webhook 

### ISSUE THREAD

**Issue by Advtech92** [Commit451/skyhook#33]
When I attempt to ping the webhook I am using, Unity Build doesn't send the ping. When pasting the url in  my search bar, I get a blank http page that says Cannot GET /api/webhooks/*CENSORED FIRST PART*/iMRNTtx3UxSevTkv7FZ9Yi74G-Sap_ZmAEsVuYCbUrjROjU7Ly5wNn19uxT_q2VoLGAf/unity.

This occurs both via the website and manually doing it.
Please let me know if you need more details.
---
Steps to recreate error:
1. Paste URL from webhook in site
2. Paste New URL in Unity Cloud Build Webhook Section
3. All options are on. 
---
Steps Taken to fix:
1. Used Pre-existing known working Webhook URL -> Same error
2. Used a New webhook URL -> Same error
3. Used Alternate Site with Pre-Existing URL -> No Error
4. Used Alternate Site with new URL -> No Error.

**Comment by Jawnnypoo** [comment]
This is intentional, you want to POST at the webhook, not GET. Web browsers will make a GET request when you paste the URL into the bar.

You can use Postman or something similar to POST to the URL

https://www.getpostman.com/

Can you try this and see if it is still a problem?

**Comment by Advtech92** [comment]
Using Postman to run POST on the URL in question returns an error 504. Ran the test twice to verify, both test resulted in the 504 error

**Comment by Jawnnypoo** [comment]
Are you including the correct JSON body, as defined here:
https://build-api.cloud.unity3d.com/docs/1.0.0/index.html#operation-webhooks-intro

**Comment by Advtech92** [comment]
I am somewhat confused by what you're asking. I thought you suggested getting postman to test the url that I got from the site to determine why it was not pinging?

**Comment by dscalzi** [comment]
Could you see if this is still an issue? When I was working on the Trello provider I found that I was unable to create a webhook for this exact reason. Trello first checks the webhook URL for a 200 status code to ensure that they arent sending payloads to dead links. In order to have that work with Skyhook I added a line of code that simply returns a 200 status code on get requests. See that change here https://github.com/Commit451/skyhook/blob/master/server.js#L38

**Comment by Advtech92** [comment]
now when you paste the link in the search bar, you get an OK, but the ping still isn't getting through from unity to discord.

**Comment by Jawnnypoo** [comment]
So this sounds more like it might be a bug with Unity payloads more than anything?

**Comment by Advtech92** [comment]
It's been working fine for a few days now since I posted this original issue. I am not sure what was wrong but it works now. It may just be an issue with the test payload and not the actual payload

**Comment by Jawnnypoo** [comment]
Hmm, okay well I'll close it out for now. Thanks!
