### ISSUE TITLE
copyToClipboard is not a function

### ISSUE THREAD

**Issue by toby3d** [Commit451/skyhook#34]
I put my discord-link `https://ptb.discordapp.com/api/webhooks/3245...` to input, select BitBucket and click on Generate, but nothing happens with this error:
![image](https://user-images.githubusercontent.com/5412322/27775207-4f579666-5fb9-11e7-90a6-61008bb57465.png)

**Comment by dscalzi** [comment]
I'm not having this issue, are you using the latest version of Chrome?

**Comment by toby3d** [comment]
@dscalzi I use latest Vivaldi browser (1.10.867.42 (Stable channel) (64bit)) on Linux.

**Comment by Jawnnypoo** [comment]
By chance do you have javascript disabled for your browser? @toby3d

**Comment by toby3d** [comment]
@Jawnnypoo No. And AdBlock disabled, of cource.

**Comment by toby3d** [comment]
It seems this problem is no longer observed. At least - after updating the browser by today's patch.
