### ISSUE TITLE
Patreon webhooks?

### ISSUE THREAD

**Issue by toby3d** [Commit451/skyhook#35]
Documentation is here: https://www.patreon.com/platform/documentation/webhooks

**Comment by dscalzi** [comment]
Do you know how I could test the payloads?

**Comment by Jawnnypoo** [comment]
You could use Postman to mock up the payloads

**Comment by dscalzi** [comment]
I need a way to trigger them because they arent documented.

**Comment by dscalzi** [comment]
@toby3d The Patreon webhooks are only triggered when a creator gets a new patron, or a patron edits/deletes their pledge (as specified by the API). I cannot trigger these webhooks as I don't have any patrons nor do I expect to get any in the forseeable future. If you have a patreon, could you help me out so I could check the payloads?

**Comment by toby3d** [comment]
> @dscalzi I may have found a way to test it, gonna see how it goes.

How? o_0
