### ISSUE TITLE
Codacy Support?

### ISSUE THREAD

**Issue by LewisTehMinerz** [Commit451/skyhook#42]
Hi there,

I would find it really useful if we had Codacy support (which has support for webhooks).

Payload:
```json
{
   "commit": {
      "data": {
         "uuid": "<uuid>",
         "urls": {         
            "delta": "https://www.codacy.com/public/<user>/<repo>.git/commit?bid=<bid>&cid=<cid>"
         }
      },
      "results": {
         "fixed_count": 1,
         "new_count": 0
      }
   }
}
```

`commit.data.urls.delta` should be the link used for the url on the embed.
Two fields used on the embed should be `Fixed Issues` and `New Issues`, which use the values `commit.results.fixed_count` and `commit.results.new_count` respectively.

Thanks,

Lewis

**Comment by LewisTehMinerz** [comment]
Willll dooooo

**Comment by LewisTehMinerz** [comment]
Looks good.

**Comment by Jawnnypoo** [comment]
Deployed!
