### ISSUE TITLE
Uncaught TypeError: window.copyToClipboard is not a function

### ISSUE THREAD

**Issue by ddouglas493** [Commit451/skyhook#46]
Unable to generate webhooks via the Skyhook website.

From the looks of the error message in the Developers Console on Chrome it is unable to pull a script for copying the webhook to the clipboard.

```
skyhook.glitch.me/:196 GET https://wzrd.in/standalone/copy-to-clipboard@latest net::ERR_INSECURE_RESPONSE
client.js:41 Uncaught TypeError: window.copyToClipboard is not a function
    at HTMLButtonElement.<anonymous> (client.js:41)
    at HTMLButtonElement.dispatch (jquery-2.2.1.min.js:3)
    at HTMLButtonElement.r.handle (jquery-2.2.1.min.js:3)
(anonymous) @ client.js:41
dispatch @ jquery-2.2.1.min.js:3
r.handle @ jquery-2.2.1.min.js:3
```

**Comment by ddouglas493** [comment]
Can confirm that the relay is still working after manually creating a url and plugging it into Bitbucket

**Comment by Jawnnypoo** [comment]
Looks like https://wzrd.in/ has an expired SSL certificate. Great

**Comment by Jawnnypoo** [comment]
Here is the relevant issue:
https://github.com/jfhbrook/wzrd.in/issues/173

**Comment by ddouglas493** [comment]
Did u attempt that curl command that is in the comments to pull the file
ignoring the certificate error and hosting locally till he can fix it?
