### ISSUE TITLE
GitLab Timeout

### ISSUE THREAD

**Issue by VerHext** [Commit451/skyhook#51]
Hello,

I´ve created a Discord - GitLab Webbhook link with this website: https://skyhook.glitch.me/
But GitLab sent me this Error:

`Hook execution failed: Net::ReadTimeout`

How can I fix this error?

Pleas help me. Thanks...

**Comment by Jawnnypoo** [comment]
Is this still occurring?

**Comment by Jawnnypoo** [comment]
Probably just had some downtime on Glitch.com
