### ISSUE TITLE
Patreon hooks doesn't work

### ISSUE THREAD

**Issue by toby3d** [Commit451/skyhook#54]
Patreon make changes in API and allow send all event types on one webhook. So, in test I get error:
```
Test Response
---
Error: HTTPSConnectionPool(host='skyhook.glitch.me', port=443): Read timed out. (read timeout=10)
```

**Comment by dscalzi** [comment]
I'll look into it.

**Comment by dscalzi** [comment]
skyhook.glitch.me is down, the patreon provider is likely fine.

@Jawnnypoo something seems to be up with the site

**Comment by Jawnnypoo** [comment]
Seems to be back up 👍

**Comment by toby3d** [comment]
Nope:
![default](https://user-images.githubusercontent.com/5412322/31986242-1da61e4a-b981-11e7-9c41-cb95dd41300e.png)

**Comment by dscalzi** [comment]
That's because the site is down again, please verify that the site is up before you report provider issues. If the site is offline, then of course the provider won't work.

**Comment by dscalzi** [comment]
@Jawnnypoo is the downtime due to glitch or is there some error on skyhook?
