### ISSUE TITLE
Material Components error in management web page

### ISSUE THREAD

**Issue by Dahlgren** [Commit451/skyhook#69]
**material-components-web.min.js:54**
```
Uncaught Error: (mdc-auto-init) Could not find constructor in registry for MDCTextfield
    at Object.i (material-components-web.min.js:54)
    at client.js:5
```

This also gives a visual error,

![screencapture-skyhook-glitch-me-1510651706470](https://user-images.githubusercontent.com/288631/32772875-9e27f9e8-c927-11e7-92b6-7126268ab07b.png)

This occurs on the linked site too, https://skyhook.glitch.me/

**Comment by dscalzi** [comment]
Issue has been resolved by reverting back to version 0.8.0 (5c90c41fb12f59ede064449753c4d0116e8dd526), see #72 for progress on upgrading to the latest version.
