### ISSUE TITLE
[Proposal] Bitbucket Provider

### ISSUE THREAD

**Issue by dscalzi** [Commit451/skyhook#7]
Hello, I have a proposal for this service. Many people use Bitbucket as a git hosting solution and currently there exists no public way to connect Bitbucket webhooks to discord. I would find it amazingly useful if a bitbucket provider could be added to this service. Many others may find this useful aswell.

I would take on the burden of this task myself, however I'm not a Javascript programmer. Also, I am not entirely sure how I would go about testing a bitbucket provider. I would definately be willing to assist someone in creating this, however I don't think I have enough knowledge to do this entirely myself.

Information on Bitbucket's webhook payloads can be found on https://confluence.atlassian.com/bitbucket/manage-webhooks-735643732.html

**Comment by Jawnnypoo** [comment]
Looks like this is closed with https://github.com/Commit451/skyhook/pull/8
