### ISSUE TITLE
Bitbucket Server support

### ISSUE THREAD

**Issue by colingalindo** [Commit451/skyhook#70]
Bitbucket server webhook responses are different than bitbucket cloud
https://confluence.atlassian.com/bitbucketserver/event-payload-938025882.html
vs
https://confluence.atlassian.com/bitbucket/event-payloads-740262817.html

**Comment by Wild1145** [comment]
This would explain why it has not been playing ball and timing out when I've been trying to get it to work...

**Comment by Artuto** [comment]
Bump?

**Comment by abenhamo** [comment]
any news on this?

**Comment by dscalzi** [comment]
We aren't working on this, but would be willing to review a PR.

**Comment by cryptic-ai** [comment]
#143 should fix this too

**Comment by Jawnnypoo** [comment]
Thanks for adding support! 🎉

**Comment by abenhamo** [comment]
now I have another error message:
Skyhook Error
An error has occured on skyhook for your webhook with provider bitbucketserver. Maybe you can copy/paste or screenshot this error if there is no sensitive information and open an issue on the skyhook GitHub.

Error: "TypeError: Cannot read property 'toRef' of undefined\n at BitBucketServer.extractPullRequestRepositoryName (/app/dist/provider/BitBucketServer.js:224:38)\n at BitBucketServer.formatPrPayload (/app/dist/provider/BitBucketServer.js:182:37)\n at BitBucketServer.<anonymous> (/app/dist/provider/BitBucketServer.js:141:18)\n at Generator.next (<anonymous>)\n at /app/dist/provider/BitBucketServer.js:7:71\n at new Promise (<anonymous>)\n at __awaiter (/app/dist/provider/BitBucketServer.js:3:12)\n at BitBucketServer.pullrequestFulfilled (/app/dist/provider/BitBucketServer.js:140:16)\n at BitBucketServer.<anonymous> (/app/dist/provider/BaseProvider.js:58:33)\n at Generator.next (<anonymous>)"

using: Atlassian Bitbucket v5.1.3

**Comment by cryptic-ai** [comment]
@abenhamo this was built for Bitbucker Server 7.1, can you send me a sanitized version of your webhook payload?

**Comment by abenhamo** [comment]
do you have an idea how can I intercept the webhook payload sent by Bitbucketserver?

**Comment by cryptic-ai** [comment]
If you go to the repository settings, you should see a webhooks setting option. If you click on the failed message you should be able to see the payload. Click on that and then the request tab, and send that but make sure you take out sensitive information

![image](https://user-images.githubusercontent.com/11448029/79228204-0de69780-7e2f-11ea-8b0d-3ccc9443e120.png)

**Comment by abenhamo** [comment]
Unfortunately, the plugin i'm using is post webhook and it has no log event
![image](https://user-images.githubusercontent.com/37488042/79228730-3d62c780-7e62-11ea-82cb-25a26835bdc5.png)

**Comment by cryptic-ai** [comment]
Ah, this only supports the native Webhooks plugin. Can you upgrade your Bitbucket Instance?

**Comment by abenhamo** [comment]
the problem, that I don't even have the native webhook plugin, it seems to be installed but no button for it

**Comment by cryptic-ai** [comment]
On the right side of your screenshot, click the edit button. Also are you in the discord server? Might be easier to discuss this there

**Comment by abenhamo** [comment]
here we go https://discord.gg/Z5KUKj

**Comment by cryptic-ai** [comment]
This was determined to be a version issue

**Comment by abenhamo** [comment]
Thank you for the support
