### ISSUE TITLE
Trello "Moved Card" Emote not working

### ISSUE THREAD

**Issue by Seklfreak** [Commit451/skyhook#73]
The emote for moving a card to a different list is not displaying (tested on MacOS and Android).
Example: ![screen shot 2017-12-06 at 20 43 03](https://user-images.githubusercontent.com/1156226/33681862-1677209a-dac6-11e7-9087-0864d75ce933.png)

I think replacing it with a `➡` should fix it.

Code in question: https://github.com/Commit451/skyhook/blob/8edf1dba5142def8331b95f2573edd2200c07a31/providers/trello.js#L719

**Comment by dscalzi** [comment]
The symbol is part of Unicode 7.0 (June 2014) which was released in 2014. The current unicode version is 10.0 (June 2017). This is ultimately an issue with the operating systems in question not supporting modern features, as Windows and modern browsers support up to unicode 9.0 (June 2016). As such, this will not be changed.

**Comment by Seklfreak** [comment]
I wasn't able to see the icon on an up to date iOS version, discordapp.com in Chrome on MacOS and discordapp.com in Edge on Windows 10 either. It does work in the Chrome, and the Discord App on Windows 10.

I think replacing the icon with the one I posted above will make it visible to on all modern systems. It seems like a simple fix to me, to make skyhook more useful on a lot of systems.

**Comment by dscalzi** [comment]
The arrow we use is a pretty common symbol, and the other arrow automatically becomes an emote in Discord which won't work with the layout. I haven't exhaustively tested where this symbol is supported but it's at least on Windows and Chrome + Firefox on Windows.

I would suggest submitting an issue with the respective softwares, as this symbol should be supported..

Edge: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/
Android: https://source.android.com/setup/report-bugs#bug-queues
Apple (Mac OS X & iOS): https://developer.apple.com/bug-reporting/

Thank you

**Comment by dscalzi** [comment]
@Seklfreak Quick update, I've posted issues on the trackers for MS Edge and Android. I don't have any apple devices so I am not able to submit a proper report on Apple's issue tracker. I would strongly recommend you submit an issue with them. The general issue to report is that the [Supplemental Arrows-C unicode block](https://en.wikipedia.org/wiki/Supplemental_Arrows-C) is not supported.

**Comment by Seklfreak** [comment]
@dscalzi Thank you very much for submitting issues to the Android and Microsoft Edge bug tracker. I created an issue at the Apple bug tracker. 👍
