### ISSUE TITLE
Bitbucket Commit Limit

### ISSUE THREAD

**Issue by Mochnant** [Commit451/skyhook#81]
Looks like there is a limit of 5 commits for Bitbucket due to Discord message limits (see #23).  For those of us who tend to batch things up locally before a push, this can lose a lot of activity.

If the messages are now shortened to 256 characters by Skyhook, and we have 4,000 to work with in Discord, even assuming other message data, the 5 limit seems a little short.

That said, might I suggest that instead of a commit limit, the total message size is tracked and truncated as needed?

Additionally, in the case where commits need to be left off, a short message along the lines of "Additional X commits not displayed." would be useful.

**Comment by Mochnant** [comment]
It may be that the Discord limit is 2,000, but even in that case, tracking the size and only truncating when the limit is full would still be a good fix.

In conjunction or seperately, breaking the commits into multiple messages would also be a good fix.

**Comment by TeoTwawki** [comment]
I actually came here looking at the same thing with gitlab. says 20 commits were pushed and gives a summery for 4 of them in a single message. That push actually had 42 commits in it. 

I'm losing a lot of activity. I have a channel specifically for commit messages only, and I'd really like to just have as much info as possible reach the discord even if that means a lot of messages in a short period. 

All 42 are not in the data sent from gitlab so getting everything would be impossible, but it would still be nice to optionally get *more* than just the last handful.

**Comment by TeoTwawki** [comment]
same here, private repository with a public commit log

**Comment by Mochnant** [comment]
@dscalzi @Jawnnypoo Sorry to bother, but does this seem like something reasonable?  Anything I can do to assist getting it done?

**Comment by dscalzi** [comment]
It could be done. Alternatively we can switch the gitlab + bitbucket providers to use the same style as Discord's built in system.

![image](https://user-images.githubusercontent.com/9703873/39851372-774332d2-53e4-11e8-9a16-eccd2b5ca939.png)

It would look similar to this.

Let me know what you think.

**Comment by Mochnant** [comment]
@dscalzi Thanks for the reply.

If I am noticing the changes, it is showing the full commit count number, but still limiting to 5 commit messages.  It also looks to have removed the perhaps extraneous "Commit from Mochnant" line that is there now.

That's an improvement, but with my and @TeoTwawki's use case, the repo is private, so the missing commit messages are really the issue.  I think the ideal fix would be to parse the commit messages into as many Discord messages as needed, and indicate that there are multiple messages.

For example, the above could add a line like "Message 1 of 4" and then 2 and 3 would have 5 each and 4 would have 3.

It would also be possible to actually track the message sizes, which would surely allow more than 5 commit message per Discord message.

Thanks for considering it!

**Comment by TeoTwawki** [comment]
I'm happy with any adjustments that get me the most info I can (multiple messages are ok :+1: ) without breaking everyone else's use case (I understand others might find single large messages annoying or multiple messages spammy). Even a compromise that gets me more total commit info into my channel is a plus.

**Comment by dscalzi** [comment]
There are only 5 commits in the above image because that's all they was pushed. It can handle more.

**Comment by Mochnant** [comment]
I was confused by the "18 new commits" vs the 5 commit messages that were actually shown.  Does the potential new message format fit as many as it can into the Discord limit?  So it would vary based on commit message length?  I notice the commit message truncation is a little more aggressive than it is currently, which with my use case, would be a downside.  This commit message is all the audience will see, and I write them with that intent (so they are a little more descriptive and less technical than I normally would).

Like @TeoTwawki, I'd be happy with any improvement, but my ideal would be full commit messages (or truncated at a high # of characters), followed by as many commits as can fit in each Discord message, and multiple messages if required.  I do understand that may be the most work, and I appreciate the consideration.

**Comment by dscalzi** [comment]
I was looking over the Bitbucket specification, only the most recent 5 commits are sent.

![image](https://user-images.githubusercontent.com/9703873/42299723-0b207984-800d-11e8-89dc-a46bca95f8a5.png)

Read more here https://confluence.atlassian.com/bitbucket/event-payloads-740262817.html.

**Comment by Mochnant** [comment]
@dscalzi Would that not mean that Skyhook would just need to call this multiple times?  Unless I am missing something that does not seem to be a blocker that would prevent improving Skyhook regardless of a bitbucket limit on the # of commits in a single call.

**Comment by dscalzi** [comment]
Bitbucket will only send 5 commits, we have no way to get anymore. Any change would need to be made with Bitbucket's webhook system.

**Comment by Mochnant** [comment]
I see your point, we would need to *start* with Bitbucket, and I have already submitted a ticket to Atlassian.  However, the Skyhook code further restricts this based on the Discord message limits, so this would need to be changed in both places.

**Comment by TeoTwawki** [comment]
Similar limits with github and gitlab payloads?

**Comment by dscalzi** [comment]
Seems like GitHub has a limit of 20, but Discord's implementation limits it to 5. https://developer.github.com/v3/activity/events/types/#pushevent

GitLab also has a limit of 20.
https://docs.gitlab.com/ee/user/project/integrations/webhooks.html#push-events

Looking over the GitHub documentation, I see that we could potentially make a followup request to get more commits. 
`https://api.bitbucket.org/2.0/repositories/{Account}/{Repo}/commits/`

Reopening this for further consideration.

**Comment by dscalzi** [comment]
I'm not sure that having an overly verbose payload would be suitable for most applications. The best way to resolve this would probably be to add another endpoint `bitbucket-verbose` or something like that. It would be a new provider, but simply extending the main one. The push function would need to be overriden on the verbose implementation.

As for sending multiple messages.. the current setup does not support that. Changes would need to be made to support that.

**Comment by dscalzi** [comment]
I've decided that this is beyond the scope of what we are trying to achieve with skyhook. I'm not going to add support for this, but I would be happy to review a PR for a verbose provider.

**Comment by dscalzi** [comment]
I don't see how that would be possible with our current setup + bitbucket's implementation. Feel free to do some research on it.

**Comment by TeoTwawki** [comment]
I'm the guy on gitlab. I got the full 20 commit messages.

**Comment by Mochnant** [comment]
For anyone still interested, this is the feature request:
https://bitbucket.org/site/master/issues/18855/event-payload-commit-truncation
