### ISSUE TITLE
Doing GET request on webhhok

### ISSUE THREAD

**Issue by AL1L** [Commit451/skyhook#91]
I am trying to add a webhook to Trello, but when I do, I get the error ```URL (https://skyhook.glitch.me/api/webhooks/476133366023061514/fcFcMYuT_W0AlGF8aTJBddYQWxxxxxxxxxxxxxxxxxxxxxxxxxGg-jhKJb/trello) did not return 200 status code, got 400```

Could doing GET requests return a status code of 200? Or am I doing something wrong?

**Comment by AL1L** [comment]
I used to be able to add webhooks with no problems a while ago, but now it's not working.

**Comment by dscalzi** [comment]
Will be fixed when @Jawnnypoo syncs the site 👍

**Comment by Jawnnypoo** [comment]
Should be good to go now
