### ISSUE TITLE
GitLab CI issue

### ISSUE THREAD

**Issue by ICTman1076** [Commit451/skyhook#93]
I've no idea what happened (hence the vague title) but I will tell you as much as I can.

I was working on a project attached to a private gitlab repo. All has been working fine, no issues like this have cropped up before. I was working on a branch, `forms`, which I then merged into `dev`. Forms locally was one commit ahead of forms remotely, and local dev was 2 commits ahead of remote dev (including the merge commit). I then pushed the two commits on my local dev branch to the remote dev branch.

We then have Gitlab CI automatically upload it to our server. This is where the 2 errors appeared.

![https://ictman.tk/img/070818_03-11-08.png](https://ictman.tk/img/070818_03-11-08.png)

The interesting thing is that I can't see which message caused the error - all the messages seemed to come through just fine.

Anyway, here's the error in text form. Both errors seem the exact same.

```
An error has occured on skyhook for your webhook with provider gitlab. Maybe you can screenshot this error and open an issue on the skyhook GitHub. Error: "TypeError: Cannot read property 'name' of undefined\n    at GitLab.<anonymous> (/app/dist/providers/GitLab.js:173:92)\n    at Generator.next (<anonymous>)\n    at /app/dist/providers/GitLab.js:6:71\n    at new Promise (<anonymous>)\n    at __awaiter (/app/dist/providers/GitLab.js:2:12)\n    at GitLab.build (/app/dist/providers/GitLab.js:172:16)\n    at GitLab.<anonymous> (/app/dist/model/BaseProvider.js:56:33)\n    at Generator.next (<anonymous>)\n    at fulfilled (/app/dist/model/BaseProvider.js:3:58)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"
```

**Edit:** Definitely a CI issue. I cancelled a CI job, and the error appeared again:
![https://ictman.tk/img/070818_03-22-54.png](https://ictman.tk/img/070818_03-22-54.png)

**Comment by Jawnnypoo** [comment]
I think this should be fixed now. Please let me know if it comes back up.

**Comment by ICTman1076** [comment]
Unfortunately, does not appear so. It has simply become an embed.
![https://ictman.tk/img/080818_10-43-54.png](https://ictman.tk/img/080818_10-43-54.png)

**Comment by szczepix** [comment]
#92 It's look like same issue to Bitbucket

**Comment by dscalzi** [comment]
Will be fixed when the site is synced.

**Comment by Jawnnypoo** [comment]
Nice, just synced it
