### ISSUE TITLE
BitBucket anonymous user error

### ISSUE THREAD

**Issue by Gabik21MC** [Commit451/skyhook#96]
If an issue is created by an anonymous user this error is printed multiple times.

Error: "TypeError: Cannot read property 'avatar' of undefined\n at BitBucket.extractAuthor (/app/dist/provider/Bitbucket.js:300:48)\n at BitBucket.<anonymous> (/app/dist/provider/Bitbucket.js:135:38)\n at Generator.next (<anonymous>)\n at /app/dist/provider/Bitbucket.js:6:71\n at new Promise (<anonymous>)\n at __awaiter (/app/dist/provider/Bitbucket.js:2:12)\n at BitBucket.issueCreated (/app/dist/provider/Bitbucket.js:134:16)\n at BitBucket.<anonymous> (/app/dist/provider/BaseProvider.js:57:33)\n at Generator.next (<anonymous>)\n at fulfilled (/app/dist/provider/BaseProvider.js:3:58)"

**Comment by Jawnnypoo** [comment]
I believe this should be resolved now.
