### ISSUE TITLE
An error has occured on skyhook for your webhook with provider bitbucket

### ISSUE THREAD

**Issue by szczepix** [Commit451/skyhook#98]
Releated to #92 
Test discord server: https://discord.gg/SRRecW2
Test bitbucket repository: https://bitbucket.org/szczepix/skyhook_test/src

When I merged pull request with checked
- [ ] Close source branch
I have bottom error:

Skyhook Error
`An error has occured on skyhook for your webhook with provider bitbucket. Maybe you can copy/paste or screenshot this error if there is no sensitive information and open an issue on the skyhook GitHub.`

`Error: "TypeError: Cannot read property 'length' of undefined\n at BitBucket.<anonymous> (/app/dist/provider/Bitbucket.js:60:46)\n at Generator.next (<anonymous>)\n at /app/dist/provider/Bitbucket.js:6:71\n at new Promise (<anonymous>)\n at __awaiter (/app/dist/provider/Bitbucket.js:2:12)\n at BitBucket.repoPush (/app/dist/provider/Bitbucket.js:48:16)\n at BitBucket.<anonymous> (/app/dist/provider/BaseProvider.js:57:33)\n at Generator.next (<anonymous>)\n at fulfilled (/app/dist/provider/BaseProvider.js:3:58)\n at process._tickCallback (internal/process/next_tick.js:68:7)"`

![image](https://user-images.githubusercontent.com/1363477/44152681-722288f2-a0a6-11e8-917b-ae0686422af4.png)

This is my webhook setup:

![skyhook_test_01](https://user-images.githubusercontent.com/1363477/44152751-9ea24106-a0a6-11e8-9ec9-c01e046bf4c5.png)

Tell me if you need repository admin or webhook url.

**Comment by szczepix** [comment]
#92

**Comment by Jawnnypoo** [comment]
Thanks for the detailed report! This should be fixed now, I hope. Please feel free to reopen if you see this again.

**Comment by szczepix** [comment]
Sorry but it's back again...

**Comment by szczepix** [comment]
Sorry but it's back again...

**Comment by szczepix** [comment]
Sorry but it's back again...
