### ISSUE TITLE
An error has occured on skyhook for bitbucket

### ISSUE THREAD

**Issue by szczepix** [Commit451/skyhook#99]
@Jawnnypoo I cannot open #98 so I create new one but it's again same problem as in #98 and #92

**Comment by Puyodead1** [comment]
Same!

**Comment by dscalzi** [comment]
Please attach the webhook body. I've asked for this several times.

**Comment by szczepix** [comment]
**It exist only for:**

![image](https://user-images.githubusercontent.com/1363477/44456490-fa0a7400-a600-11e8-80c2-1bd491aefae6.png)

**Webhook body:**

![image](https://user-images.githubusercontent.com/1363477/44456252-54ef9b80-a600-11e8-9cff-a5bc8d14c47d.png)

**Comment by dscalzi** [comment]
That is not the webhook body.

Setup skyhook locally (https://github.com/Commit451/skyhook/blob/master/CONTRIBUTING.md#local-testing) and intercept the webhook. Print the body to the console.

It will look similar to this. https://github.com/Commit451/skyhook/blob/master/test/bitbucket.json

**Comment by szczepix** [comment]
**Requests statuses:**

![image](https://user-images.githubusercontent.com/1363477/44482822-b9831880-a649-11e8-9b8c-4913fc6a3161.png)

**Comment by dscalzi** [comment]
This appears to be an issue whenever a tag is pushed to the repository. I will start working on a solution.

**Comment by dscalzi** [comment]
This will be fixed next time @Jawnnypoo syncs the site. The payload will look like this:

![image](https://user-images.githubusercontent.com/9703873/44486898-d9531600-a622-11e8-8bc5-41794a7a610d.png)

**Comment by Jawnnypoo** [comment]
Done!
